### ISSUE TITLE
Packages requiring 3rd party install repository

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#10]
The packages in the following table have no known archived install locations from the publisher:

| Package ID | Publisher URL | 3rd party repository | Associated issues |
| --- | --- | --- | --- |
| adobeshockwaveplayer | [Latest URL](http://www.adobe.com/go/sw_slim_exe_installer) | FileHippo.com | https://github.com/dtgm/chocolatey-packages/issues/9 |
### Please Help

If you know of an archived location to retrieve previous versions from the publisher, please either
- create a new issue with a reference pointing to this issue to prevent clutter, or
- send a message by clicking **Contact Maintainers** from the package's page at http://www.chocolatey.org 
  
  > Example: http://www.chocolatey.org/packages/adobeshockwaveplayer/ContactOwners)

**Comment by tunisiano187** [comment]
@gep13, this one is maintained by @pauby and EOL
so this issue can be closed too.

Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for checking this
