### ISSUE TITLE
Rejected packages that should not have been

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#100]
from back on 24 Aug 2015 
>I rejected some packages I shouldn't have rejected because I missed a small point in the package naming guidelines (that it is ok to omit spaces) and I would like to undo the damage. Mostly dtgm's packages were affected. 

List of packages that were rejected, but should not have been. Requested package status to be changed to SUBMITTED.

- [x] https://chocolatey.org/packages/acm/1.00
- [x] https://chocolatey.org/packages/accesspv/1.12
- [x] https://chocolatey.org/packages/asterie/1.03
- [x] https://chocolatey.org/packages/axhelper/1.12
- [x] https://chocolatey.org/packages/empv/1.00
- [x] https://chocolatey.org/packages/faview/1.32
- [x] https://chocolatey.org/packages/folrep/1.21
- [x] https://chocolatey.org/packages/hostinfo/1.0.1
- [x] https://chocolatey.org/packages/iconsext.install/1.47
- [x] https://chocolatey.org/packages/iconsext.install/1.47.0.20150708
- [x] https://chocolatey.org/packages/iehv/1.70
- [x] https://chocolatey.org/packages/mweather.install/1.73
- [x] https://chocolatey.org/packages/mweather/1.73
- [x] https://chocolatey.org/packages/mzcv/1.50
- [x] https://chocolatey.org/packages/passwordscan.install/1.33
- [x] https://chocolatey.org/packages/passwordscan/1.33
- [x] https://chocolatey.org/packages/passwordscan.install/1.35
- [x] https://chocolatey.org/packages/passwordscan/1.35
- [x] https://chocolatey.org/packages/pcanypass/1.12
- [x] https://chocolatey.org/packages/pcanyscan/1.0
- [x] https://chocolatey.org/packages/shman/1.10
- [x] https://chocolatey.org/packages/split/1.0
- [x] https://chocolatey.org/packages/tflash/1.00
- [x] https://chocolatey.org/packages/timestamp/1.1
- [x] https://chocolatey.org/packages/using/1.30
- [x] https://chocolatey.org/packages/win9xpv/1.1
- [x] https://chocolatey.org/packages/wul.install/1.32
- [x] https://chocolatey.org/packages/wul/1.32
- [x] https://chocolatey.org/packages/zipinst/1.21
- [x] https://chocolatey.org/packages/bluetoothcl/1.00
- [x] https://chocolatey.org/packages/bluetoothcl/1.07
- [x] https://chocolatey.org/packages/conadvpass/1.01
- [x] https://chocolatey.org/packages/cprocess/1.13
- [x] https://chocolatey.org/packages/ctie/1.01
- [x] https://chocolatey.org/packages/dllexp/1.63

**Comment by gep13** [comment]
@dtgm ok, I think I got them all.  Let me know if I missed any.

**Comment by dtgm** [comment]
@gep13 just added 1 more

https://chocolatey.org/packages/bluetoothcl/1.00

**Comment by dtgm** [comment]
@gep13 and

https://chocolatey.org/packages/texniccenter/2.02

**Comment by gep13** [comment]
@dtgm that is me away to sign off for the night, been a long day, but if there are any more, added them here, and I will pick them up tomorrow.

**Comment by dtgm** [comment]
@gep13 have a good one :beers:

**Comment by ferventcoder** [comment]
@dtgm using? You asked for that one to be rejected.

**Comment by ferventcoder** [comment]
@dtgm passwordscanner is waiting on fixes.

**Comment by ferventcoder** [comment]
https://chocolatey.org/packages/bluetoothcl/1.00 should be 1.07.

**Comment by dtgm** [comment]
@ferventcoder 

* `using` should be, and is, rejected
* [passwordscan-1.35](https://chocolatey.org/packages/passwordscan/1.35) status should be changed to submitted
* bluetoothcl = fixed

**Comment by gep13** [comment]
@dtgm passwordscan status has been changed to submitted.
