### ISSUE TITLE
Consolidate sysinternals pstools programs

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#106]
The following **13** packages use the same install URL and should be consolidated:

psexec/2.11
psfile/1.02
psgetsid/1.44
psinfo/1.77
pskill/1.14
pslist/1.30
psloggedon/1.34
psloglist/2.71
pspasswd/1.23
psping/2.01
psservice/2.24
psshutdown/2.52
pssuspend/1.06

https://download.sysinternals.com/files/PSTools.zip

Ref: https://github.com/dtgm/chocolatey-packages/issues/70#issuecomment-167629466

**Comment by dtgm** [comment]
`psversion.txt` within downloaded zip currently lists version as `2.45`
From modified timestamp of that file, it appears 2.45 was released `2016.04.21`, but other files have newer timestamp of `2016.06.28` so actual version may be `2.45.x.y`

No version is listed at pstools webpage: https://technet.microsoft.com/sysinternals/pstools 
Published date is May 2, 2014, but that is not getting updated.

https://chocolatey.org/packages/pstools is maintained by ferventcoder who is not tracking version either. Last package uploaded was `1.2012.04.11` on 2012.04.11

However, *none* of the individual packages have had their versions changed from their respective technet homepage from was listed in [previous comment](https://github.com/dtgm/chocolatey-packages/issues/106#issue-132721035)

ToDo: I need to find location where versions are accurately being tracked.

**Comment by dtgm** [comment]
```posh
dir *.exe | %{& $_.name -v >> tmp}
```

```bash
iconv -f utf16 -t utf8 tmp > t
grep -P '^\w+\sv[\d.]+(?= \- )' t -o | uniq
```
or similar in posh
```posh
sls "^\w+\sv[\d.]+(?= - )" tmp | select matches
```

PsExec v2.2
PsFile v1.03
PsGetSid v1.45
PsInfo v1.78
PsKill v1.16
PsList v1.4
PsLoggedon v1.35
PsPasswd v1.24
PsPing v2.10
PsService v2.25
PsSuspend v1.07

program | 02-10 | 06-30
--- | --- | ---
psexec | 2.11 | 2.20
psfile | 1.02 | 1.03
psgetsid | 1.44 | 1.45
psinfo | 1.77 | 1.78
pskill | 1.14 | 1.16
pslist | 1.30 | 1.40
psloggedon | 1.34 | 1.35
psloglist | 2.71 | ?
pspasswd | 1.23 | 1.24
psping | 2.01 | 2.10
psservice | 2.24 | 2.25
psshutdown | 2.52 | ?
pssuspend | 1.06 | 1.07

**Every program was upgraded**. But none had their corresponding https://technet.microsoft.com/sysinternals/pssuspend page reflect that.

**Comment by tunisiano187** [comment]
@gep13 i think this one can be closed, as that's maintained by ferventcoder and the package isn't checking sha so... not linked to a version

**Comment by gep13** [comment]
@tunisiano187 based on the Disqus comments for the package in question, I believe that there is still some work to be done, but I agree that it isn't the responsibility of this repository.
