### ISSUE TITLE
git-annex install problems

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#107]
Messagebox popup

git-annex Setup
ahk_class #32770
ahk_exe git-annexInstall.exe

Button1
OK

> You need git installed to use git-annex. Looking at C:\Program Files (x86)\Git, it seems to not be installed, or may be installed in another location. You can install git from http://git-scm.com/

Dependency on git-annex for https://chocolatey.org/packages/git

By default, on Win10 64-bit :  
-  `git` installs to `$env:ProgramFiles`
- `git-annex` installs to `${env:ProgramFiles(x86)}`

Install is not logged to registry

```
C:\PROGRAM FILES (X86)\GIT
│   git-annex-licenses.txt
│   git-annex-uninstall.exe
│
├───cmd
│       git-annex-autostart.vbs
│       git-annex-webapp.vbs
│       git-annex.cmd
│
├───mingw32
│   └───share
│       └───doc
│           └───git-doc
│                   git-annex.html
│
└───usr
    └───bin
            git-annex.exe
            rsync.exe
            wget.exe
```

**Comment by gep13** [comment]
This package is no longer maintained in this repository, so this issue can be closed out.
