### ISSUE TITLE
Change package status to SUBMITTED

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#112]
Failed to fix on time so these packages are currently rejected. Please revert to submitted so I may fix.

- [ ] https://chocolatey.org/packages/fontmatrix/0.6.0
- [ ] https://chocolatey.org/packages/i2p/0.9.20
- [ ] https://chocolatey.org/packages/isoplex/2.7.0
- [ ] https://chocolatey.org/packages/izpack/4.3.5
- [ ] https://chocolatey.org/packages/keepass-plugin-databasereorder/2.09
- [ ] https://chocolatey.org/packages/keepass-plugin-gost/1.4
- [ ] https://chocolatey.org/packages/keepass-plugin-keecloud/1.2.0.1
- [ ] https://chocolatey.org/packages/lyx/2.1.4
- [ ] https://chocolatey.org/packages/multibit/0.5.18.20150723
- [ ] https://chocolatey.org/packages/myeventviewer/2.20
- [ ] https://chocolatey.org/packages/netpass
- [ ] https://chocolatey.org/packages/npackd-cli.portable/1.20.5
- [ ] https://chocolatey.org/packages/popcorntime/0.3.8.5
- [ ] https://chocolatey.org/packages/projectlibre/1.6.2
- [ ] https://chocolatey.org/packages/QTTabBar/1038.0
- [ ] https://chocolatey.org/packages/redshift/1.10
- [ ] https://chocolatey.org/packages/retroshare/0.6.0.8551
- [ ] https://chocolatey.org/packages/sniffpass
- [ ] https://chocolatey.org/packages/sniffpass.install
- [ ] https://chocolatey.org/packages/soluto/1.3.1497.1
- [ ] https://chocolatey.org/packages/sonarr/2.0.0.3243
- [ ] https://chocolatey.org/packages/tinycad/2.80.08.631
- [ ] https://chocolatey.org/packages/truecrypt/7.1.20150620
- [ ] https://chocolatey.org/packages/uniextract.portable/1.6.1
- [ ] https://chocolatey.org/packages/videocacheview/2.95
- [ ] https://chocolatey.org/packages/wirelessnetview/1.68
- [ ] https://chocolatey.org/packages/zimbra-desktop/7.2.7
- [ ] https://chocolatey.org/packages/zona/1.0.6.8

**Comment by ferventcoder** [comment]
Done.

**Comment by ferventcoder** [comment]
Sqllitebrowser also
