### ISSUE TITLE
automatic dirs missing a corresponding XML

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#122]
directories in https://github.com/dtgm/chocolatey-packages/tree/master/automatic that do not have a corresponding XML in https://github.com/dtgm/chocolatey-packages/tree/master/ketarin

inverse issue: https://github.com/dtgm/chocolatey-packages/issues/123

these directories are typically **new** or **handover** packages
- [ ] adblockplussafari
- [ ] adbputty
- [ ] adh
- [ ] advancedsystemcare
- [ ] aida64-neaudit
- [ ] atom
- [ ] blackcoin
- [ ] bluebeamrevu
- [ ] darkcoin
- [ ] darkcoin.install
- [ ] darkcoin.portable
- [ ] digikam
- [ ] dsc.psdesiredstateconfiguration
- [ ] erchangesview
- [ ] ertimeupdate
- [ ] hexed
- [ ] honeyproxy
- [ ] httpnesniffer
- [ ] hwinfo.NEEDS-HEADERS
- [ ] it
- [ ] keepass-plugin-ewalletdatalib
- [ ] keepass-plugin-g
- [ ] keepass-plugin-keeform
- [ ] keepass-plugin-s
- [ ] locate
- [ ] manictime
- [ ] manictime.install
- [ ] manictime.portable
- [ ] mongodb.install
- [ ] mongodb.portable
- [ ] mremoteng
- [ ] neconnectlog
- [ ] neinterfacesview
- [ ] nelatencyview
- [ ] netrafficview
- [ ] opcion
- [ ] procexp
- [ ] procmon
- [ ] quantummoves
- [ ] shellmen
- [ ] sickbeard
- [ ] specialersview
- [ ] subtitlshop
- [ ] subtitlshop.install
- [ ] subtitlshop.portable
- [ ] syncany-cli
- [ ] sysinternal-template
- [ ] template-all
- [ ] template-exe-inno
- [ ] template-exe-nsis
- [ ] template-metapkg
- [ ] template-msi
- [ ] tor
- [ ] urbackup-server
- [ ] vcredist2008
- [ ] vcredist2013

**Comment by gep13** [comment]
I don't think we need a tracking issue for this problem, or the inverse.
