### ISSUE TITLE
XML pkgs missing a corresponding automatic dir

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#123]
XML in https://github.com/dtgm/chocolatey-packages/tree/master/ketarin that do not have a corresponding directory in https://github.com/dtgm/chocolatey-packages/tree/master/automatic

inverse issue: https://github.com/dtgm/chocolatey-packages/issues/122

these XML files are typically **deprecated** or **obsolete** pkgs that need to be cleaned up by integrating notes into the production XML file
- [ ] acr
- [ ] adobeshockwaveplayer [DEP]
- [ ] adwcleaner [bleeping URLs expire after 10 min]
- [ ] aida64-networkaudit
- [ ] allmyapps
- [ ] arcthemall
- [ ] arduinoide
- [ ] asteroiddatahunter
- [ ] audioswitcher (sf.net)
- [ ] bitcoin -- broke
- [ ] bitcoinxt (alt)
- [ ] bitcoinxt.install (alt)
- [ ] bluebeam
- [ ] books
- [ ] cdex (sf.net)
- [ ] copy
- [ ] daemontoolslite
- [ ] debugview
- [ ] dependencywalker
- [ ] designsparkpcb
- [ ] desura
- [ ] digiKam
- [ ] diskusage(du)
- [ ] djvulibre
- [ ] doxbox
- [ ] driverbooster
- [ ] DSC.PSDesiredStateConfiguration
- [ ] dumeter
- [ ] duplicati.beta
- [ ] easybcd
- [ ] filetool [googlecode]
- [ ] firefox-dev [sometimes works]
- [ ] folderchangesview
- [ ] foldertimeupdate
- [ ] foldit
- [ ] gamebooster
- [ ] githubforwindows
- [ ] heroesofnewerth
- [ ] hotswap
- [ ] ht
- [ ] httpnetworksniffer
- [ ] hwinfo
- [ ] internet
- [ ] jstock (previous alphabet releases)
- [ ] keepass-plugin-
- [ ] keepass-plugin-sf
- [ ] kicad beta
- [ ] line
- [ ] llftool
- [ ] lyx [mirror]
- [ ] md5-and-sha-checksum-utility
- [ ] md5deep [sourceforge]
- [ ] midori-browser
- [ ] mipony
- [ ] mkvtoolnix
- [ ] mongodb [MSI]
- [ ] mozbackup
- [ ] mremoteng.portable
- [ ] mRemoteNG
- [ ] mucommander
- [ ] munin-nude
- [ ] networkconnectlog
- [ ] networkinterfacesview
- [ ] networklatencyview
- [ ] networktrafficview
- [ ] nircmd (already exists)
- [ ] nirsoft.util.all
- [ ] novacoin
- [ ] officetabenterprise
- [ ] onedrive
- [ ] PasswordSafe (Windows Setup)
- [ ] pokerth
- [ ] processexplorer
- [ ] processmonitor
- [ ] psiphon [MANUAL]
- [ ] qt-sdk
- [ ] qupzilla
- [ ] registryusage(ru)
- [ ] revouninstallerpro
- [ ] rmprepusb
- [ ] rollbackrx
- [ ] sabnzbd.install
- [ ] sabnzbd.portable
- [ ] sandboxie.beta
- [ ] sandboxie.portable
- [ ] sanerpersonal
- [ ] SciTE (Windows Installer) [32]
- [ ] settings
- [ ] shellmenunew
- [ ] simplesystemtweaker
- [ ] smartmontools 1 (not choco compatible)
- [ ] smartmontools 2 (messy 301 redirect hack)
- [ ] smartmontools [md5]
- [ ] songr
- [ ] specialfoldersview
- [ ] sss
- [ ] startisback
- [ ] startisbackplus
- [ ] stunnel.beta
- [ ] subtitleworkshop.install
- [ ] subtitleworkshop.portable
- [ ] subtitleworkshop
- [ ] tcpview
- [ ] tdesktop
- [ ] tdsskiller
- [ ] template-sysinternals
- [ ] Template.Ketarin-program-command
- [ ] texworks
- [ ] tflash210
- [ ] tinytask
- [ ] ultravnc-forum
- [ ] ultravnc2
- [ ] ums [corrupt XML]
- [ ] usbit
- [ ] using
- [ ] ut-launcher
- [ ] veracrypt (already exists, codeplex)
- [ ] viber
- [ ] wassapp
- [ ] wincontig
- [ ] winscp [main]
- [ ] winscp.install [main]
- [ ] x
- [ ] xulrunner
- [ ] x_padding
- [ ] [DEPRECATED] sandboxie.beta
- [ ] [DEPRECATED] tdesktop
- [ ] [MANUAL] hddguardian

**Comment by gep13** [comment]
I don't think we need a tracking issue for this problem, or the inverse.
