### ISSUE TITLE
chocolatey gallery pkg 'strings' is not what I expected

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#130]
[strings](https://chocolatey.org/packages/Strings) is a powershell module. I expected this to be Sysinternals program of the same name that is a clone of GNU's binutils program, strings.

Maintainer [Jaykul](https://chocolatey.org/profiles/Jaykul) seems to be inactive and hasn't responded to an email sent 20160119. 

In that email I suggested his powershell modules might be better placed on a private feed if he was no longer maintaining them.

**Comment by tunisiano187** [comment]
@gep13 , this one isn't a real issue linked to this repo, so i think you can remove it.
Thanks

**Comment by gep13** [comment]
@tunisiano187 agreed.
