### ISSUE TITLE
popcorntime

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#131]
https://gist.github.com/choco-bot/2d32559dbc58431cb4e4#file-install-txt-L230-L235

> Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."

**Comment by dtgm** [comment]
dead: https://popcorntime.io/

2016.01.25 https://chocolatey.org/packages/popcorntime#comment-2477778663
>New Popcorn time :: http://popcorn-time.se/

which redirects to http://popcorn-time.to and also noted

2016.05.11 https://chocolatey.org/packages/popcorntime#comment-2670714702
> New PopcornTime http://popcorn-time.to

But that points to beta `5.4` whereas last package version automatically discovered built on chocolatey was `0.3.9`

Those appear to be closed source re-releases of the original popcorntime. They provide the source for an old version of popcorntime, but the changes made in the new versions do not provide the associated source code.

2016.02.24 https://blog.popcorntime.sh/official-statement/
> We're no longer in active development. Most of our old teammates have left the ship to focus on a new technology, they called it Butter, and we use their platform as a base to make Popcorn Time. 

The last version available from https://popcorntime.sh is beta 0.3.9

The associated package was built and uploaded, but rejected due to an auto-testing issue.
https://chocolatey.org/packages/popcorntime/0.3.9
https://gist.github.com/2d32559dbc58431cb4e4

**Comment by tunisiano187** [comment]
@gep13 , this issue can be closed, i'm taking this package.
the package is ready on my git.
Thank you
