### ISSUE TITLE
standardize automatic packages

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#137]
### Overview

`Automatic packages` leverage open-source `ketarin` from data in `XML` files to identify updated versions available and then build the `nupkg`
### Goal

Make using others' ketarin files ubiquitous so anyone can more easily integrate others' XML files into their build process.
### Procedure
1. Identify users utilizing ketarin to update packages and push those updates to Chocolatey.org
2. Identify shared repositories where these files are being stored
3. Identify areas of improvement for sharing

**Comment by dtgm** [comment]
#### auto repositories

found auto repositories based on published profile data on user page

https://github.com/dtgm/chocolatey-packages/
https://github.com/chocolatey/chocolatey-coreteampackages
https://github.com/ferventcoder/chocolatey-packages
https://github.com/jivkok/Chocolatey-AutomaticPackages
https://github.com/aronovgj/choco-auto
https://github.com/segilbert/nuget.packages.git
https://github.com/dhilgarth/chocolatey-packages/tree/master/automatic
https://github.com/kireevco/chocolatey-packages
https://github.com/narnaud/chocolatey-packages
https://github.com/Link-Satonaka/chocopkgs
https://github.com/okhoshi/chocolatey-packages
https://github.com/Vaquero84/chocolatey-packages/tree/master/automatic
https://github.com/chocolatey/chocolatey-coreteampackages
https://github.com/Thilas/chocolatey-packages
https://github.com/daftspaniel/Chocolatey-Packages/
https://github.com/Laures/chocolatey-packages
https://github.com/esabine/chocolateyautomaticpackages
https://github.com/Kristinn-Stefansson/krschocolateypackages
https://github.com/majkinetor/chocolatey
https://github.com/0-F/chocolatey-package/tree/master/packages
https://github.com/030/chocolateyautomatic
https://github.com/ComFreek/chocolatey-packages
https://github.com/glachance/Chocolatey
https://github.com/ootaken/chocolatey
https://github.com/WCOMAB/nugetpackages
https://github.com/DanyO/ChocolateyPackages
https://github.com/emipa606/chocolatey
http://www.myget.org/F/tfchocolatey/

**Comment by dtgm** [comment]
#### Clone all repos

`gc .\list.txt | %{Invoke-Expression "git clone $($_).git"}`

**Comment by dtgm** [comment]
#### Quantity XML files in each

`gci -dir * | %{"$((gci $_ -recurse -include *.xml).count) `| $($_.name)"}`

Qty | `username_reponame`
--- | :---
0 | 0-F_chocolatey-package
5 | 030_chocolateyautomatic
6 | aronovgj_choco-auto
151 | chocolatey_chocolatey-coreteampackages
4 | ComFreek_chocolatey-packages
0 | daftspaniel_Chocolatey-Packages
1 | DanyO_ChocolateyPackages
16 | dhilgarth_chocolatey-packages
1073 | dtgm_chocolatey-packages
0 | emipa606_chocolatey
1 | esabine_chocolateyautomaticpackages
364 | ferventcoder_chocolatey-packages
0 | glachance_Chocolatey
0 | jivkok_Chocolatey-AutomaticPackages
3 | kireevco_chocolatey-packages
2 | Kristinn-Stefansson_krschocolateypackages
0 | Laures_chocolatey-packages
20 | Link-Satonaka_chocopkgs
0 | majkinetor_chocolatey
10 | narnaud_chocolatey-packages
6 | okhoshi_chocolatey-packages
1 | ootaken_chocolatey
0 | segilbert_nuget.packages
3 | Thilas_chocolatey-packages
15 | Vaquero84_chocolatey-packages
0 | WCOMAB_nugetpackages

**Comment by tunisiano187** [comment]
@gep13 , i think this one can be closed too, many maintainers are using AU now, so that's not relevant anymore.
Thank you

**Comment by gep13** [comment]
@tunisiano187 agreed.  This would have been a great issue to get completed at the time, but I think automatic packaging has moved on a lot towards AU.
