### ISSUE TITLE
ketarin: standardize settings

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#138]
#137

Note: out of about 28 automatic repos, only 3 publish the ketarin settings being used; kristinn     aronovgj, and dtgm
### How users currently have ketarin configured

| Option | Default | kristinn | aronovgj | core | ferventcoder | dtgm |
| --- | :-: | :-: | :-: | :-: | :-: | :-: |
| **GENERAL** |  |  |  |  |  |  |
| Update auto at startup |  |  |  |  |  |  |
| Avoid beta version on FileHippo |  |  |  | X |  | X |
| Check for updates in the online database | X | X | X | X |  |  |
| Minimize to tray |  |  | X |  |  | X |
| Auto create database backups | X | X | X |  |  | X |
| Open website when double-clicking on an app |  |  |  |  |  |  |
| Columns |  |  | 1 | 1 | 1 | 15 |
| Version {version} |  |  | X | X | X | X |
| **CONNECTION** |  |  |  |  |  |  |
| Connection timeout | 10 | 10 | 30 | 15 |  | 60 |
| Number of threads | 2 | 2 | 20 | 3 |  | 4 |
| Number of retries | 1 | 1 | 3 | 2 |  | 2 |
| **GLOBAL VARIABLES** |  |  |  |  |  |  |
| * |  |  |  |  |  | 10 |
| 7z |  |  |  |  |  | X |
| curl |  |  |  |  |  | X |
| wget |  |  |  |  |  | X |
| workdir |  |  |  |  |  | X |
| chocoPkgOutput |  |  |  |  |  | X |
| ie32 |  |  |  |  |  | X |
| ie64 |  |  |  |  |  | X |
| firefox |  |  |  |  |  | X |
| opera |  |  |  |  |  | X |
| chrome |  |  |  |  |  | X |
| **COMMANDS** |  |  |  |  |  |  |
| Before updating an application |  | 1 | 2 | 3 |  | 4 |
| After updating an application |  |  |  |  |  | 1 |
| After updating all applications |  |  |  |  |  |  |

**Before updating an application**
1. `chocopkgup /p {appname} /v {version} /u "{preupdate-url}" /u64 "{url64}" /pp {file} /disablepush`
2. `chocopkgup "{nopush}" /p {appname} /v {version} /u "{preupdate-url}" /u64 "{url64}" /pp "{file}"`
3. `chocopkgup /p "{appname}" /v "{version}" /u "{preupdate-url}" /u64 "{url64}" /pp "{file}"`
4. `chocopkgup {nopush} --packagename={appname} --version={version} --pg="{packageGuid}" --url="{preupdate-url}" --urlx64="{url64}" --packagepath="{file}" --checksum="{checksum}" --c64="{checksumx64}" --debug`

**After updating an application**
1. cscript

**After updating all applications**
1.

**Comment by dtgm** [comment]
### Others' recommendations

[chocolatey-coreteampackages](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/bin/README.md)

**Comment by dtgm** [comment]
#### Maintain common variable naming

https://github.com/chocolatey/choco/wiki/CommandsNew#usage

`maintainername` >> `maintainerName`
`maintainerrepo` >> `maintainerRepo`

**Comment by dtgm** [comment]
### Proposed Ketarin Global Variables

#### `workdir `

* propose replacing `workdir` with `saveDir`
* ketarin local path where binary files are saved

#### `maintainerName`

* same as username on `https://chocolatey.org/profiles/maintainerName`
* populates `<owners>` element in nuspec

#### `maintainerRepo`

* git repo URL where pkgs are stored
* populates `<packageSourceUrl>` element in nuspec

**Comment by dtgm** [comment]
### Suggested custom columns

Name | Value | Example 
--- | --- | ---
Version | `{version}` | 0.0.19
fileDate | `{f:yyyy}-{f:MM}-{f:dd} {f:HH}:{f:mm}` | 2015-11-21 15:15
Progress |  |  
fileSize | `{filesize:formatfilesize}` | 
Target |  | 
fixedUrl | `{property:FixedDownloadUrl:regex:(?<=//).*?(?=/)}` | 
user-agent | `{property:UserAgent}` | 
referer | `{property:HttpReferer}` | 
host | `{url:regex:(?<=//)([\w-]+\.)*(?=[\w-]+\.[\w-]+(?=/))}` | 
domain | `{url:regex:(?<=//[\w-]+\.)*[\w-]+\.[\w-]+(?=/)}` | 
Category |  | 
packageGuid | `{packageGuid}` | 
Status |  | 
varChgInd | `{property:VariableChangeIndicator}` | 
cscript | `{cscript}` | 2
enabled | `{property:Enabled}` | True
nopush | `{nopush}` | 
checksum64file | `{checksum64file}` | 
delPrevFile | `{property:DeletePreviousFile:multireplace:,:True,False:X,}` | `X`

**Comment by tunisiano187** [comment]
@gep13 ,
as most of the repos are now using au, o think this can be closed.
Thx

**Comment by gep13** [comment]
@tunisiano187 agreed.
