### ISSUE TITLE
[Feature][All] check for addition/removal of start-menu entries

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#14]
For example: 

[snes9x v1.53.*](https://chocolatey.org/packages/snes9x/1.53.0.20150220) does not add start-menu entry

**Comment by tunisiano187** [comment]
@gep13, i think you now, but i'll tell you ;-)
You can close this one ;-)

**Comment by gep13** [comment]
@tunisiano187 makes sense, thanks!
