### ISSUE TITLE
using markdown in chocolatey.org review comments

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#143]
for application somewhere here: https://github.com/chocolatey/chocolatey.org/issues

``````
``` << code blocks using triple backticks do not work
``````
#### Attempt 1

Writing in review comment:

```
### Command line usage
* `docfx help`
```

will be rendered as

---
### Command line usage
- `docfx help`

---
#### Attempt 2

Code blocks do not work.  
Writing in review comment:

``````
```
### Command line usage
* `docfx help`
```
``````

will be rendered as

---

```
### Command line usage
- `docfx help`

```

---
### Solution

Write in review comment:

```
`### Command line usage`
\* \`docfx help\`
```

Escape rendering by:
- surround character to escape with single backticks ` 
- preface character to escape with `\`

**Comment by tunisiano187** [comment]
This was just a hint, i think that it can be closed @gep13

**Comment by gep13** [comment]
@tunisiano187 agreed.  The markdown rendering engine on chocolatey.org was also recently changed, so this investigation work would likely be needed to be done again if there was still an issue.
