### ISSUE TITLE
use Control* where possible

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#144]
use [ControlSend](https://autohotkey.com/docs/commands/ControlSend.htm) In place of `Send`,`SendRaw`,`SendInput`,`SendPlay`,`SendEvent`

``` powershell
ControlSend [, Control, Keys, WinTitle, WinText, ExcludeTitle, ExcludeText]
```

use [ControlClick](https://autohotkey.com/docs/commands/ControlClick.htm) In place of `Click`,`MouseClick`,`Send {Click}`,`MouseClickDrag`,`MouseMove`

``` powershell
ControlClick [, Control-or-Pos, WinTitle, WinText, WhichButton, ClickCount, Options, ExcludeTitle, ExcludeText]
```

**Comment by dtgm** [comment]
**18** AHK files using `Send*`
```bash
$ for i in */tools/*.ahk; do grep -i '^\s*Send[ ,]\|SendRaw\|SendInput\|SendPlay\|SendEvent' $i -m1 -l; done
activetcl/tools/chocolateyUninstall.ahk
avgantivirusfree/tools/chocolateyInstall.ahk
avginternetsecurity/tools/chocolateyInstall.ahk
bitmeteros/tools/chocolateyInstall.ahk
cdex/tools/chocolateyInstall.ahk
fontforge/tools/chocolateyUninstall.ahk
github/tools/githubInstall.ahk
i2p/tools/chocolateyInstall.ahk
i2p/tools/chocolateyUninstall.ahk
izpack/tools/chocolateyUninstall.ahk
mtn/tools/chocolateyInstall.ahk
qttabbar/tools/chocolateyInstall.ahk
qttabbar/tools/chocolateyInstallPost.ahk
softwareinformer/tools/chocolateyUninstall.ahk
soluto/tools/solutoInstall.ahk
soluto/tools/solutoUninstall.ahk
sumo/tools/sumoInstall.ahk
superantispyware/tools/chocolateyUninstall.ahk
```

**Comment by dtgm** [comment]
**3** AHK files using Click...

```bash
$ for i in */tools/*.ahk; do grep -i '^\s*Click\|MouseClick\|Send[ ,]{Click}\|MouseClickDrag\|MouseMove'  $i -m1 -l; done
soluto/tools/solutoUninstall.ahk
superorca/tools/chocolateyInstall.ahk
zona/tools/chocolateyInstall.ahk
```

**Comment by tunisiano187** [comment]
Hi @gep13 , this one can be closed too
the milestone linked too
Have a nice day.
tunisiano

**Comment by gep13** [comment]
@tunisiano187 what makes you say this one can be closed? I think the work suggested here is still a good idea, no?

**Comment by tunisiano187** [comment]
Yes, but he won't do that anymore, and i'm taking his packages and doing it my side... but if you think it should stay,.. no problem

**Comment by gep13** [comment]
@tunisiano187 as long as this is on your radar when you bringing packages into your repository, then I am happy for this to be closed.

**Comment by tunisiano187** [comment]
FYI : https://github.com/tunisiano187/Chocolatey-packages/issues/16
