### ISSUE TITLE
Identify installers that manipulate running tasks

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#149]
Some installers may kill running processes during install or restart processes/services.

At best this is annoying.  
At worst, this can cause data loss.
1. Identify which processes stop (kill,upgrade) running processes/services.
2. Identify which processes restart (kill,upgrade,start) running processes/services.
3. Especially those installers that manipulate `explorer.exe`

**Comment by tunisiano187** [comment]
@gep13 , i think this one won't be fixed.
so it may be closed

**Comment by gep13** [comment]
Agreed!
