### ISSUE TITLE
[Feature][All] coordinate naming between package managers

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#15]
#### Debian dpkg

Package system == dpkg
Package format == dpkg
Package manager == apt-get, aptitude

https://packages.debian.org, also https://www.debian.org/distrib/packages
#### Gentoo portage/ebuild/emerge

Package system == portage
Package format == ebuild
Package manager == emerge

http://packages.gentoo.org/categories/
#### [rpm](http://rpm.org/)

Package system == rpm
Package format == rpm
Package manager == yum

http://rpmfusion.org/
yum - Redhat/Fedora/CentOS
SUSE/openSUSE
Meego
Mageia

See: https://github.com/dtgm/chocolatey-packages/wiki/%5BAll%5D-coordinate-naming-between-package-managers

**Comment by tunisiano187** [comment]
@gep13 , this one can be closed too i think.
Have a nice day

**Comment by gep13** [comment]
@tunisiano187 agreed.
