### ISSUE TITLE
nirlauncher not creating shims for ~80 programs

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#152]
Since the program names are the same for 64 and 32 bit, only one will get created as a shim.... so ~80 or so programs don't have an associated shim generated.

Note that not all 32-bit programs have an associated 64-bit executable.

**Comment by dtgm** [comment]
* 199 32-bit exes
* 83 64-bit exes

Confusingly, 1 of the 64-bit exes ends with "32": `volumouse32.exe` and the 32-bit version omits the `32`: `volumouse.exe`. That is the only exception. All the other 64-bit exes have the same program name as their 32-bit version.

Only 1 other 64-bit exe contains a number: `nk2edit.exe` and the same name is used for the 32-bit version.

Best option seems to be rename all the 64-bit executables by appending 64 and changing 32 to 64 for volumouse32.exe to be consistent.

**Comment by dtgm** [comment]
Also, this package could really use conflicts/replaces/provides tags once that becomes available or some logic in handling conflicting packages.

**Comment by dtgm** [comment]
#### Need to allow only install of 32-bit programs

Since 32-bit and 64-bit programs are packaged in same ZIP file, 32-bit versions get overwritten by 64-bit always. 

Installing only 32-bit is not currently possible with `nirlauncher` package

#### Investigating how to handle conflict with individual packages

Looking at packages `nirlauncher` and `driverview`:

* 32-bit: nirlauncher.zip\NirSoft\driverview.exe
* 64-bit: nirlauncher.zip\NirSoft\x64\driverview.exe
* 32-bit: driverview.zip\DriverView.exe
* 64-bit: driverview-x64.zip\DriverView.exe

So this shouldn't be a problem.

**Comment by ferventcoder** [comment]
Why would you install both?

**Comment by ferventcoder** [comment]
Ah, you could generate ignore files depending on the architecture. This is widely used.

**Comment by dtgm** [comment]
`.ignore` files are an option and I've used this method in other pkgs, but I think that maybe I shouldn't have for situations like this. 

I'm thinking best practice would be to remove unnecessary files if a user specifies only 32-bit as I probably shouldn't pollute `tools` with unwanted files, bloating the install. And reserve using `.ignore` files for things like included dependent exes where a generated shim is not desired.

**Comment by ferventcoder** [comment]
Fair enough.

**Comment by majkinetor** [comment]
I fixed this by moving x64 programs one dir above overwriting x32 bit programs (only on 64bit platforms).

I also removed shims in favor of PATH. One shim is created only, for niraluncher.exe itself.

I added this to my repo so you can exlude it in the future from your ketarin jobs.

Ref: https://github.com/majkinetor/au-packages/blob/master/nirlauncher/tools/chocolateyInstall.ps1#L25-L29

**Comment by gep13** [comment]
The nirlauncher package is no longer maintained in this repository, so going to close out this issue.
