### ISSUE TITLE
github pkg: add posh-git to path

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#154]
### add posh-git to path

> You know what would be nice, if this package added git to the System or User path so we could use git without having to open git shell specifically. It could do the same as sysinternals does and create a symlink to the chocolatey bin folder.
> 
> Also, if possible to make posh-git available without once again having to start with git-shell icon.
> 
> This stuff possible or should I just install git and posh-git packages too?

https://chocolatey.org/packages/GitHub/3.0.15.03#comment-2494132851

**Comment by tunisiano187** [comment]
@gep13 , this is maintained by another maintainer and [deprecated]
So you can close it too.

Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks
