### ISSUE TITLE
Chocolatey bit-depth handling logic

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#160]
### Summary

How to handle bit-depths (32/64) of binaries in regards to combined conditions:  
- (1) OS compatibility
- (2) User specified
- (3a) available binaries
- (3b) whether binaries are bundled or separate URL
#### 1

| OS bit-depth | OS compatibility |
| --- | --- |
| 64 | 32/64 |
| 32 | 32 |
#### 2

| User specified |
| --- |

```
--x86, --forcex86
    ForceX86 - Force x86 (32bit) installation on 64 bit systems. Defaults to false.
```
- Note 1: no `--forcex64` (sic) which means 64-bit will always install if present on 64-bit OS.
- Note 2: `--forcex86` is marked in choco to become `--force32`
#### 3a

| nupkg params defined | usage | resulting behavior | whatif issue |
| --- | --- | --- | --- |
| url | 32, 32+64, 64 | currently using regardless of installer bit-depth | only 64-bit available, but OS is 32-bit? |
| url, url64 | no issues |  |  |
| url64 | n/a | not used if only 64-bit install binary available |  |
#### 3b

if both binaries are included in one URL or separate

**Comment by dtgm** [comment]
### Case scenarios

OS | url | url64 | --force86 | Result | Expected
--- | --- | --- | --- | --- | ---
32 | 32 | - |  |  32 | 
32 | 32 | - | ✓ |  32 | 
32 | 32/64 | - |  | 64 (?) | 32
32 | 32/64 | - | ✓ | 64 (?) | 32
32 | 64 | - |  | ? | ERROR
32 | 64 | - | ✓ | ? | ERROR
32 | - | 64 |  |  | ERROR
32 | - | 64 | ✓ |  | ERROR
64 | 32 | - |  | 32 | 32
64 | 32 | - | ✓ | 32 | 32
64 | 32/64 | - |  |  | 64 
64 | 32/64 | - | ✓ |  | 32
64 | 64 | - |  | 64 | 64
64 | 64 | - | ✓ | ? | ERROR
64 | - | 64 |  | 64 | 64
64 | - | 64 | ✓ | ? | ERROR

? = untested  

### Thoughts

1. URL should change to URL32 and choco handles logic based on dependent variables of OS/User specified/nupkg. This would require storing options of nupkg so choco source feed returns packages based on OS being run on.

2. If there is no binary available for OS running choco, pkg should be marked *unavailable* or *unlisted*

3. Ability to install both 64 and 32 bit versions.

4. Would be easiest if handled automatically during pkg creation; users handle various variables, then choco pack handles figuring out the details and tweaks nupkg accordingly.

5. Auto determining various install compatibility is dependent on installer container/framework developer as well as how each program developer implements the various options available by the respective installer framework.

**Comment by tunisiano187** [comment]
@gep13 i think this one isn't required anymore.
Thanks

**Comment by gep13** [comment]
@dtgm makes sense.
