### ISSUE TITLE
Unique pkg id for each program versions (e.g. redistributables, VS, etc)

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#172]
Currently, some programs have a different package ID for each version.
#### [dotnet/netfx framework packages](https://chocolatey.org/packages?q=dotnet)
- [dotnet3.5](https://chocolatey.org/packages/dotnet)
- [dotnet4.0](https://chocolatey.org/packages/dotnet4.0)
- [dotnet4.5](https://chocolatey.org/packages/dotnet4.5)
- [dotnet4.5.1](https://chocolatey.org/packages/dotnet4.5.1)
- [dotnet4.5.2](https://chocolatey.org/packages/dotnet4.5.2)
- [dotnet4.6](https://chocolatey.org/packages/dotnet4.6)
- [dotnet4.6.1](https://chocolatey.org/packages/dotnet4.6.1)

also, (not sure how these are diff from above)
- [netfx-4.0.3-devpack](https://chocolatey.org/packages/netfx-4.0.3-devpack)
- [netfx-4.6-devpack](https://chocolatey.org/packages/netfx-4.6-devpack)
- [dotnet4.6-targetpack](https://chocolatey.org/packages/dotnet4.6-targetpack)
#### [Microsoft Visual C++ redistributables](https://chocolatey.org/packages?q=redistributable)
- [vcredist2005](https://chocolatey.org/packages/vcredist2005)
- [vcredist2008](https://chocolatey.org/packages/vcredist2008)
- [vcredist2010](https://chocolatey.org/packages/vcredist2010)
- [vcredist2012](https://chocolatey.org/packages/vcredist2012)
- [vcredist2013](https://chocolatey.org/packages/vcredist2013)
- [vcredist2015](https://chocolatey.org/packages/vcredist2015)

duplicates?
- [msvisualcplusplus2012-redist](https://chocolatey.org/packages/msvisualcplusplus2012-redist)
- [msvisualcplusplus2013-redist](https://chocolatey.org/packages/msvisualcplusplus2013-redist)
#### [Visual Studio](https://chocolatey.org/packages?q=visualstudio)
- [visualstudioexpress2008](https://chocolatey.org/packages/visualstudioexpress2008) 
- [visualstudio2012expressweb](https://chocolatey.org/packages/visualstudio2012expressweb) 
- [visualstudio2012premium](https://chocolatey.org/packages/visualstudio2012premium) 
- [visualstudio2012professional](https://chocolatey.org/packages/visualstudio2012professional) 
- [visualstudiocommunity2013](https://chocolatey.org/packages/visualstudiocommunity2013) 
- [visualstudio2013expressweb](https://chocolatey.org/packages/visualstudio2013expressweb) 
- [visualstudio2013premium](https://chocolatey.org/packages/visualstudio2013premium) 
- [visualstudio2013professional](https://chocolatey.org/packages/visualstudio2013professional) 
- [visualstudio2013ultimate](https://chocolatey.org/packages/visualstudio2013ultimate)
- [visualstudio2013teamexplorer](https://chocolatey.org/packages/visualstudio2013teamexplorer)
- [visualstudio2015community](https://chocolatey.org/packages/visualstudio2015community)
- [visualstudio2015professional](https://chocolatey.org/packages/visualstudio2015professional)

duplicates?
- [vs2012.4](https://chocolatey.org/packages/vs2012.4)
- [vs2012.5](https://chocolatey.org/packages/vs2012.5)
- [vs2013.1](https://chocolatey.org/packages/vs2013.1)
- [vs2013.2](https://chocolatey.org/packages/vs2013.2)
- [vs2013.3](https://chocolatey.org/packages/vs2013.3)
- [vs2013.4](https://chocolatey.org/packages/vs2013.4)
- [vs2013.5](https://chocolatey.org/packages/vs2013.5)
- [visualstudio2013-update1](https://chocolatey.org/packages/visualstudio2013-update1)
- [visualstudioexpress2013windows](https://chocolatey.org/packages/visualstudioexpress2013windows)
- [visualstudio2013testprofessional](https://chocolatey.org/packages/visualstudio2013testprofessional) 
- many more...

related:
- [visualstudio2013-sdk](https://chocolatey.org/packages/visualstudio2013-sdk)
- [visualstudio2012professionalwebtools](https://chocolatey.org/packages/visualstudio2012professionalwebtools)
- many more...
### Why not consolidate?

Disregarding that these are probably unnecessary duplicates, packages like:
- [vs2013.1](https://chocolatey.org/packages/vs2013.1)
- [vs2013.2](https://chocolatey.org/packages/vs2013.2)
- [vs2013.3](https://chocolatey.org/packages/vs2013.3)
- [vs2013.4](https://chocolatey.org/packages/vs2013.4)
- [vs2013.5](https://chocolatey.org/packages/vs2013.5)

Should definitely be consolidated into a single `vs2013` package

But from there, how to handle versions?
#### Option 1 -- metapackage
- visualstudio == metapackage (not fully implemented yet)
- dynamically choose version and types (community/premium/professional/ultimate) via "undecided method" similar to `FOO`/`FOO.install`/`FOO.portable`
#### Option 2 -- master pkg
- Single package for all versions and types.
- Choose **version** and **release type** via `--package-parameters`

`choco install visualstudio --params '/2013 /professional'`
`choco install visualstudio --params '/version=2013 /release=professional'`
#### Option 3 -- master type
- Single package for all **release types**.
- Choose **version** via `--package-parameters`

`choco install visualstudio-professional --params '/2013'`
`choco install visualstudio-professional --params '/version=2013'`  
#### Option 4 -- master major version
- Single package for all **versions**.
- Choose **release type** via `--package-parameters`

`choco install visualstudio2013 --params '/professional'`
`choco install visualstudio2013 --params '/release=professional'`
#### Programs
- visual-studio
- visualstudio
- vs

Examples:
- visual-studio-professional
- visualstudio-professional
- vs-professional
#### Release type

Also long-hand or short-hand for release types (if used):

| long-hand | short-hand |
| --- | --- |
| community | comm |
| express | exp |
| premium | prem |
| professional | pro |
| ultimate | ult |
### Final question (hard)

Which would be best practice? 
- most intuitive 
- maximum benefits 
- minimal disadvantages

**Comment by tunisiano187** [comment]
@gep13 , this seems OK in the version 0.10.5+
so i think you can close.
thx

**Comment by gep13** [comment]
@tunisiano187 this is a good reference issue regarding duplicate packages etc, but I agree, I don't think there is anything to be done here directly.
