### ISSUE TITLE
AWSCLI 1.10.16 version outdated

### ISSUE THREAD

**Issue by gregmac** [dtgm/chocolatey-packages#175]
AWS CLI 1.10.18 is out, and so:

    Error - hashes do not match. Actual value was 'CDB64608EB028053B87636A018EBC82AB4FB5DDC'.

Note that AWS doesn't seem to provide verisoned links, they just have one static location with the latest version available: https://s3.amazonaws.com/aws-cli/AWSCLI64.msi

This means that:

* The second AWS releases a new version, the Choclatey package will fail until the maintainer updates the hashes 
* You can't install old versions with chocolatey (you'll get a hash mismatch error)

Ideally AWS could provide a canonical, versioned link for each version (eg: https://s3.amazonaws.com/aws-cli/10.10.18/AWSCLI64.msi) but not sure if this is doable (or who to contact).

**Comment by dtgm** [comment]
> The second AWS releases a new version, the Choclatey package will fail until the maintainer updates the hashes

These get updated automatically, but there must be an issue with this package. A new version should be posted soon.

> You can't install old versions with chocolatey (you'll get a hash mismatch error)

Correct. You will want to reach out to Amazon's development team and inquire about the possibility of this. You may want to try https://github.com/aws/aws-cli/issues and report back with any news.

Unfortunately, not being able to install older packages respective of the associated program version also occurs in many other packages as well.

**Comment by gregmac** [comment]
Per the ticket above, AWS does actually provide versioned links in the form:

    https://s3.amazonaws.com/aws-cli/AWSCLI{64/32}-{version}.msi

**Comment by dtgm** [comment]
Thanks for taking the time to figure this out! 

Versions >1.10.21 will install the respective program version.
