### ISSUE TITLE
Replace  Get-BinRoot with Get-ToolsLocation 

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#179]
`Get-BinRoot` helper function is being deprecated in favor of `Get-ToolsLocation` 

~~In applicable scripts, replace:~~ NOT YET!

| old | new |
| --- | --- |
| `Get-BinRoot` | `Get-ToolsLocation` |
| `$env:ChocolateyBinRoot` | `$env:ChocolateyToolsLocation` |
| `%ChocolateyBinRoot%` | `%ChocolateyToolsLocation%` |

Ref:  
- https://github.com/chocolatey/choco/issues/631
- https://github.com/chocolatey/choco/wiki/CreatePackages#3-path-provided-by-the-get-binroot-helper---will-be-deprecated-later-closer-to-v1-but-okay-to-use-for-now

**Comment by dtgm** [comment]
Using `Get-ToolsLocation` requires also adding as dependency

```xml
<dependencies> 
  <dependency id="chocolatey" version="0.9.10" /> 
</dependencies>
```

`Get-BinRoot` is an alias for `Get-ToolsLocation` so nothing should be updated for now. Deprecated warning should be ignored for now.

**Comment by musm** [comment]
So is  `Get-ToolsLocation`  officially removed?

**Comment by tunisiano187** [comment]
Get-Binroot did, not Get-ToolsLocation

**Comment by tunisiano187** [comment]
@gep13, It seems this one can be closed too.
Thank you
