### ISSUE TITLE
Migrate existing nuspec markdown data into new metadata fields

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#18]
https://github.com/chocolatey/choco/issues/205

- [x] projectSourceUrl
- [x] packageSourceUrl
- [x] docsUrl
- [x] mailingListUrl
- [x] bugTrackerUrl
- [ ] replaces
- [ ] provides
- [ ] conflicts

**Comment by ferventcoder** [comment]
You can leave out the last 3 at the moment. 

Unless you understand what they are for. I haven't built out how they will be handled on chocolatey.org or in chocolatey yet, so basically they don't do much.

Replaces - removes existing packages if they are installed.
Provides - Hello virtuals
Conflicts - I need to research this one more to fully grok my understanding of it. :)
