### ISSUE TITLE
nsis packages are broken as their link points to 2.50

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#184]

**Comment by dtgm** [comment]
there was an issue with correctly auto-identifying the version so it's a bit of a mess at the moment.

The latest stable is 2.51 and I just pushed that package: https://chocolatey.org/packages/nsis.portable/2.51

However, the 3.x versions installs the RC and they stopped getting marked as "prerelease" so upgrading will install the RC and not the latest in 2.51.

The latest is https://chocolatey.org/packages/nsis.portable/3.01.0.20160420 but the version schema `3.01.0.20160420` should probably be `3.0-rc1` which would require removing those packages and issuing new ones. Then the latest installed would be `2.51` and the RC versions would require passing the choco parameter `-pre`

**Comment by dtgm** [comment]
https://chocolatey.org/packages/nsis./3.01.0.20160410  
https://chocolatey.org/packages/nsis.install/3.01.0.20160410  
https://chocolatey.org/packages/nsis.portable/3.01.0.20160410  

have all been unlisted from chocolatey as they pointed incorrectly to `2.50`

**Comment by TheOneRing** [comment]
Hm -pre is was I was using anyhow as I was using this package for a long time now. I just hope we get a release this decade 😄
