### ISSUE TITLE
fah: file listing denied

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#186]
Files can no longer be listed; Access Forbidden

https://fah.stanford.edu/file-releases/public/release/fah-installer/windows-xp-32bit/?C=N;O=D

**Comment by dtgm** [comment]
Requires javascript to retrieve download links?

http://folding.stanford.edu/#  
https://folding.stanford.edu/home/the-software/#

**Comment by dtgm** [comment]
Help requested and none provided https://foldingforum.org/viewtopic.php?f=16&t=28759

No known way of getting latest version.

**Comment by tunisiano187** [comment]
@gep13 , you canlose q jhis one, i'mthed mainatiner ;-)
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks
