### ISSUE TITLE
Update scraped checksums from MD5/SHA1 to SHA256 (where available)

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#197]
Currently, checksums for the binary installers downloaded by packages are handled in 1 of 2 ways:
1. (this ticket) If a checksum is publicly available from a web-scrapable page, that is used. Only MD5 and SHA1 are retrieved.
2. #196 If no checksum is available, the auto-build machine will download the installer binary and calculate the SHA1 to be used in the package.

All packages with an available SHA256 checksum should transition to that.

https://github.com/ferventcoder/choco/commit/2509f78e7f035e499c14385c3534c542868aeaa8
https://github.com/chocolatey/choco/issues/113

**Comment by dtgm** [comment]
Scope: ~154 packages use scrape to get checksum

**Comment by tunisiano187** [comment]
@gep13 , i'll manage this one with my Todo list, so it can be closed.
FYI : https://gitlab.com/chocolatey-packages/todo/-/blob/master/README.md

Thank you

**Comment by gep13** [comment]
@tunisiano187 sounds like a plan, thank you!
