### ISSUE TITLE
Checksum not matching error with winsshd.install

### ISSUE THREAD

**Issue by jtcmedia** [dtgm/chocolatey-packages#199]
winsshd.install v6.47
 Error - hashes do not match. Actual value was 'E2FF48434B0EC812AC74CA70B45FC7AB'.
 Checksum for 'C:\Users\jasonc\AppData\Local\Temp\chocolatey\Bitvise SSH Server\6.47\Bitvise SSH ServerInstall.exe' did 
 not meet '7b29e14edf637ce69837bcc5c4d2103e' for checksum type 'md5'.
 At C:\ProgramData\chocolatey\helpers\functions\Get-CheckSumValid.ps1:59 char:5
 +     throw "Checksum for `'$file'` did not meet `'$checksum`' for chec ...
 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: (Checksum for 'C...sum type 'md5'.:String) [], RuntimeException
     + FullyQualifiedErrorId : Checksum for 'C:\Users\jasonc\AppData\Local\Temp\chocolatey\Bitvise SSH Server\6.47\Bitv 
    ise SSH ServerInstall.exe' did not meet '7b29e14edf637ce69837bcc5c4d2103e' for checksum type 'md5'.
The install of winsshd.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winsshd.install\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by dtgm** [comment]
https://chocolatey.org/packages/winsshd/6.47.0.20160525
