### ISSUE TITLE
Writing bginfo .bgi file (binary) with powershell?

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#201]
[bginfo](https://chocolatey.org/packages/bginfo) writes a customization file to `.bgi`

@flcdrg I could do a "Get-Content custom.bgi" and it looks like we could do a regex replace, but I'm not sure how powershell works with writing binary files. I wonder if there is some sort of hex editing powershell cmdlets capable of replacing embedded strings...

**Comment by tunisiano187** [comment]
@gep13 , this can be closed as the package is now maintained by @flcdrg 
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks
