### ISSUE TITLE
Wrong sha256 checksum for MediaInfo 0.7.86

### ISSUE THREAD

**Issue by HakanSiktas** [dtgm/chocolatey-packages#209]
Currently the installation of MediaInfo 0.7.86 fails due to a wrong checksum in its chocolateyInstall.ps1.

In https://github.com/dtgm/chocolatey-packages/commit/3514fe6977cc7ef739b2917f86e77e40f3a9e7fa the checksum

`d8fd5f3fbefd1c262c2026e8d2defef19621ee141384d875f9fad1f557da5967`

for the file [MediaInfo_GUI_0.7.86_Windows.exe](http://mediaarea.net/download/binary/mediainfo-gui/0.7.86/MediaInfo_GUI_0.7.86_Windows.exe)  is wrong.
The correct one seems to be

`9adfecec026d59540f2f611d4decc27323b9068acb1365ae80b6bf1b52062909`.

**Comment by dtgm** [comment]
Confirmed. Tested the original exe used to create the pkg and it also had 9adfe... sum. Not sure why it decided to use the wrong sum.

**Comment by dtgm** [comment]
For the record, I'm doubtful that commit was the issue causing this since [mediainfo-cli](https://chocolatey.org/packages/mediainfo-cli/0.7.86)'s ketarin had the same issue but was not afflicted; sums were calc'd correctly for mediainfo-cli.
