### ISSUE TITLE
(RFC) "unattended" tag for packages containing AHK not intuitive

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#217]
https://gitter.im/chocolatey/choco?at=575b5c50e20024bd1ad27e46
I don't like that I decided to use `unattended` for packages containing AHK scripts ... that isn't intuitive at all is it?
I made the change of using `notSilent` to `unattended` for AHK pkgs in dtgm/chocolatey-packages#97
intuitively, it would make more sense if both of those tags were present, since using AHK may cause dialog boxes to momentarily flash on screen which would be "notSilent", but no user interaction is required, so they are also "unattended"
I guess I was hoping to combine both tags into one, but that was a flop and I don't know what I was thinking. There is probably a more intuitive way.

Reference
Changed from using notSilent to unattended for AHK pkgs in https://github.com/dtgm/chocolatey-packages/issues/97
Defined `unattended` in https://github.com/dtgm/chocolatey-packages/issues/98#issuecomment-179086002

**Comment by dtgm** [comment]
>unattended made sense when I thought it is a good idea to also have an attended tag. So for a proper package you would have no tag, for flashing screens unattended so you know something is wrong but still ok and then attended for user input packages. The tags would look similar. I thought that's nice. If we don't want packages requiring user input at all, then notsilent makes more sense. However currently it still means user input is nee
~~@aronovgj https://gitter.im/chocolatey/choco?at=575bdc281cf76dd645362a5f

**Comment by tunisiano187** [comment]
@gep13 
I think this can be deleted.
Thank you.

**Comment by gep13** [comment]
@tunisiano187 agreed.
