### ISSUE TITLE
irfanview uninstall fails

### ISSUE THREAD

**Issue by bazzilic** [dtgm/chocolatey-packages#223]
Here are installation/uninstallation logs: https://gist.github.com/bazzilic/bce58b0db1f3d8d8ca8eb85cfd680b56

My assumption is that the issue (at least partially) is in my Windows username having a space: `Sidorov Vasily`.

What is not reflected in the log is that AutoHotKey fails to to call the uninstall script with an error message "Can't open script `C:\Users\Sidorov`" — clearly an issue with the space.

Some tinkering with the uninstall scripts that I've done didn't help, but I am far from being knowledgeable about choco specifics.

**Comment by dtgm** [comment]
Thanks for creating this issue. 

I believe this has been fixed in #218. However, the fix will only roll out as new versions are released. From a quick look at https://chocolatey.org/packages/irfanview#versionhistory it appears new versions are released about 6-12 months so I'll put out a manual package fix.

**Comment by dtgm** [comment]
Should be fixed in https://chocolatey.org/packages/IrfanView/4.42.0.20160616
Please reopen if not.

**Comment by bazzilic** [comment]
Waiting for the package to undergo approval. Interestingly, automated chocolatey testing indicates that uninstall of the newly submitted package failed: https://gist.github.com/choco-bot/f63ee3bb324663e876ab454ba2545d25#file-_summary-md

**Comment by dtgm** [comment]
Correct you are sir. It looks like it is failing now due to the new helper added in `0.9.10-rc1`

https://gist.github.com/choco-bot/f63ee3bb324663e876ab454ba2545d25#file-uninstall-txt-L255

**Comment by dtgm** [comment]
You can see the tester is still on `-beta1` https://gist.github.com/choco-bot/f63ee3bb324663e876ab454ba2545d25#file-uninstall-txt-L6

**Comment by dtgm** [comment]
I added `chocolatey-uninstall.extension` as a dependency which I should have done originally.

Going through testing again.

**Comment by bazzilic** [comment]
Let's see how it goes this time.

Also, by looking at the commit #218 I don't think that'll fix the issue with the AutoHotKey, which I mentioned in the original post.

**Comment by dtgm** [comment]
I got my :dollar: that commit will work :)

**Comment by dtgm** [comment]
:moneybag: << added to the pot

**Comment by dtgm** [comment]
error occurs when trying to parse install path https://gist.github.com/bazzilic/bce58b0db1f3d8d8ca8eb85cfd680b56#file-iv-choco-uninstall-log-L273

**Comment by bazzilic** [comment]
Still fails but for a different reason :8ball:
https://gist.github.com/choco-bot/0c885e1a375778d8f232533b5306d5a3#file-uninstall-txt-L262

**Comment by dtgm** [comment]
And let that be a lesson to not :beers: and :up: !
6th times a charm?

**Comment by dtgm** [comment]
Well, it finally happened... https://gist.github.com/choco-bot/f3ede8c3bade039bea3616854d0e08e7#file-uninstall-txt-L304
