### ISSUE TITLE
KeePass Plugin: KeeAnywhere

### ISSUE THREAD

**Issue by Kyrodan** [dtgm/chocolatey-packages#224]
Could you please add KeeAnywhere for KeePass as package?
https://github.com/Kyrodan/KeeAnywhere

Info: I'm the author of this plugin.

**Comment by dtgm** [comment]
@Kyrodan Please review

New packages will be built from https://github.com/Kyrodan/KeeAnywhere/releases/latest (so releases marked as prerelease in GH, wouldn't get packaged)

I only look for the `*.plgx` file on that page.

I grab the version from the tag, not the filename (I assume you are populating the filename with the tag to set version).

`choco install keepass-plugin-keeanywhere --version 1.0.0`

**Comment by dtgm** [comment]
As mentioned, getting version from URL path with `(?<=v)[\d\.]{3,\}(?=/)`

Kyrodan/KeeAnywhere/releases/download/v1.0.0/KeeAnywhere-1.0.0.plgx
Kyrodan/KeeAnywhere/releases/download/v**1.0.0**/KeeAnywhere-1.0.0.plgx

**Comment by Kyrodan** [comment]
Hi @dtgm,

this looks good and is my preferred way of getting the package. For the future: I'm thinking about stripping version info out of the filename (because it's easier to update: just overwrite the *.plg instead of deleting the old one which contains version number).

**Comment by Kyrodan** [comment]
Ah I see, you already rename the filename when downloading. That should be ok.

**Comment by dtgm** [comment]
:) yup, I rename them to reflect the same as the chocolatey id so it is both 1) easier to uninstall package, and 2) it's clear to identify which plugins were installed with chocolatey.

I currently don't remove existing plugins, although maybe I should...(?)...or maybe just notify user if a similar plugin is found. Do you recall how KeePass determines loading of duplicate plugins? I'm thinking only the first plugin found is loaded and duplicates after are ignored....not sure.

You are safe to remove `-1.0.0` from the filename, that wouldn't affect building this package. Just be sure to use proper tagging for the new release.

**Comment by dtgm** [comment]
Also, just a day before you filed this, I filed #222 where I am looking at improving my `keepass-plugin-*` install/uninstall routines to make more robust; possibly outsourcing it into an extension. Opinions welcome on #222 :)

**Comment by dtgm** [comment]
https://chocolatey.org/packages/keepass-plugin-keeanywhere
