### ISSUE TITLE
Packages with linking to nuget.org in description

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#227]
`| Please install with chocolatey (http://nuget.org/List/Packages/chocolatey).`

$ for i in $(grep '| Please install with chocolatey' _/_.nuspec -l); do basename ${i%.*}; done
- [ ] [ack](https://chocolatey.org/packages/ack)
- [ ] [ActivePerl](https://chocolatey.org/packages/ActivePerl)
- [ ] [ChirpyVSI](https://chocolatey.org/packages/ChirpyVSI)
- [ ] [clipx](https://chocolatey.org/packages/clipx)
- [ ] [ctags](https://chocolatey.org/packages/ctags)
- [ ] [DarkRoom](https://chocolatey.org/packages/DarkRoom)
- [ ] [db-visualizer](https://chocolatey.org/packages/db-visualizer)
- [ ] [Executor](https://chocolatey.org/packages/Executor)
- [ ] [GnuWin](https://chocolatey.org/packages/GnuWin)
- [ ] [Growl](https://chocolatey.org/packages/Growl)
- [ ] [installwindowsimage.powershell](https://chocolatey.org/packages/installwindowsimage.powershell)
- [ ] [intellij-idea-ultimate](https://chocolatey.org/packages/intellij-idea-ultimate)
- [ ] [KatMouse](https://chocolatey.org/packages/KatMouse)
- [x] [P4Merge](https://chocolatey.org/packages/P4Merge) https://github.com/alanstevens/ChocoPackages/commit/cfbc43bf08554d1b0f77a35c93c395e108720782
- [ ] [ProgrammersNotepad](https://chocolatey.org/packages/ProgrammersNotepad)
- [ ] [pstools](https://chocolatey.org/packages/pstools)
- [x] [ruby.devkit](https://chocolatey.org/packages/ruby.devkit)
- [ ] [tfsSidekicks](https://chocolatey.org/packages/tfsSidekicks)
- [ ] [tfsSidekicks2010](https://chocolatey.org/packages/tfsSidekicks2010)
- [ ] [tfsSidekicks2012](https://chocolatey.org/packages/tfsSidekicks2012)
- [ ] [UAdevelopers.utils](https://chocolatey.org/packages/UAdevelopers.utils)
- [ ] [winmerge](https://chocolatey.org/packages/winmerge)

^^^ remove line

**Comment by tunisiano187** [comment]
@gep13, i've checked, and the updated version seems removing this line and the other software are unmaintained anymore.
So i think we can close this.
Thank you

**Comment by gep13** [comment]
@tunisiano187 sounds like a plan.
