### ISSUE TITLE
IrfanView v4.42.0.20160616 uninstall is not silent

### ISSUE THREAD

**Issue by bazzilic** [dtgm/chocolatey-packages#232]
Still not a charm... :)

Uninstallation of the IrfanView package creates windows that expect user input (e.g., "Are you sure you want to delete IrfanVew? yes/no"), requires user interaction to create an elevated process for AutoHotKey, and then fails to launch the AutoHotKey script.

![capture](https://cloud.githubusercontent.com/assets/1805832/16355538/e58b53be-3aeb-11e6-9837-febdedc050d0.PNG)

**Comment by gep13** [comment]
@bazzilic I am going to go ahead and close out this issue, as this package is no longer hosted on this repository.  It is being maintained by @bcurran3.  Thanks.
