### ISSUE TITLE
freefilesync checksum issues

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#234]
#### Problem

https://chocolatey.org/packages/freefilesync#comment-2752610302

> ![screenshot of checksum failure](https://a.disquscdn.com/uploads/mediaembed/images/3859/4345/original.jpg?w=800&h)
#### Cause

Url points to latest version of `major.minor` http://www.freefilesync.org/download/FreeFileSync_8.2_Windows_Setup.exe

It appears new builds are 
- not noted anywhere
- instead of releasing a `major.minor.build` the `.build` is wrapped into `major.minor` and the installer is re-compiled.
#### Effect

`choco upgrade freefilesync` will install different versions for users at different times with no way of upgrading except blindly forcing a reinstall every so often. Although it is also unclear what exactly is changing in the install EXE.

more details: https://chocolatey.org/packages/freefilesync#comment-2762673028
open inquiry: http://www.freefilesync.org/forum/viewtopic.php?t=2799

**Comment by tunisiano187** [comment]
currently maintained by @teknowledgist asked today to update it.
currently here : https://github.com/teknowledgist/Chocolatey-packages/tree/master/discontinued/freefilesync

**Comment by gep13** [comment]
@tunisiano187 thanks for following up on this one.
