### ISSUE TITLE
VBoxVmService newer version

### ISSUE THREAD

**Issue by bazzilic** [dtgm/chocolatey-packages#237]
Hi!

The version of VboxVmService in the package registry is 4.1.2.1: https://chocolatey.org/packages/vboxvmservice
Newer version 5.1 is available: https://sourceforge.net/projects/vboxvmservice/files/vboxvmservice/Versions%205.x/

**Comment by tunisiano187** [comment]
Hi @bazzilic,
I see you're the new maintainer of this package.
Can you remove the folder from automatic and the file in ketarin and submit a PR?

Thank you

**Comment by gep13** [comment]
I have removed the required files in this commit: https://github.com/dtgm/chocolatey-packages/commit/821da4ceafb0548c948bf1073e78bfc3b78bad9d
