### ISSUE TITLE
NUnit packages not picking up v3.4.1

### ISSUE THREAD

**Issue by ChrisMaddock** [dtgm/chocolatey-packages#239]
The NUnit packages have not been updated to v3.4.1. I think the site may have changed, in redirecting to the GitHub releases page, rather than a direct download from nunit.org.

Related: have also restarted the discussion over NUnit doing the packaging, over on nunit/nunit#452

**Comment by CharliePoole** [comment]
@ChrisMaddock @gep13 This issue can be closed, since we now release the packages from the NUnit project.

**Comment by ChrisMaddock** [comment]
Thanks @CharliePoole
