### ISSUE TITLE
[ultravnc] Switch to .EXE

### ISSUE THREAD

**Issue by C-Duv** [dtgm/chocolatey-packages#240]
It seems the .exe's options `/loadinf` and `/dir` (see http://www.uvnc.com/docs/uvnc-server.html > "Automate Installation") are not available through _.msi_ (which this package is using) and there is no workaround.
A solution is to use the _.exe_ installer, as it can be made as silent as the _.msi_ by using `/silent` or `/verysilent` arguments.

**Comment by tunisiano187** [comment]
@gep13 , this one can be closed, it's maintained by mkevenaar
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for confirming.

**Comment by C-Duv** [comment]
Hi, I see you closed the issue: it's a "WONT FIX case" then?

**Comment by tunisiano187** [comment]
It's maintained by @mkevenaar , not by dtgm, so i'm trying to clean here, but with this tag, he will see this issue

**Comment by tunisiano187** [comment]
after verification, he's using the exe file like you're asking.
Have a nice day

**Comment by C-Duv** [comment]
OK, I see.
I didn't noticed the package changed repository.

Thank you for the info and checking 👍.
