### ISSUE TITLE
[keepass-plugin-keeanywhere] Handover

### ISSUE THREAD

**Issue by Kyrodan** [dtgm/chocolatey-packages#243]
Please remove `keepass-plugin-keeanywhere` from your package source as I would like to maintain it by myself.

I already got maintainer rights and pushed a new version.

**Comment by dtgm** [comment]
Thank you for letting me know. I've disabled this package from auto-updating for now.

**Comment by CWempe** [comment]
I guess this can be closed. Right?

**Comment by tunisiano187** [comment]
@gep13 this is solved and the PR is #534 
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks
