### ISSUE TITLE
Bitvise SSH Server has checksum mismatch

### ISSUE THREAD

**Issue by jnm2** [dtgm/chocolatey-packages#246]
```
Error - hashes do not match. Actual value was '4F9AE0E25750CED53796B70E91631969'.
```

Not sure if I should send a PR- do you just blindly assume that's the new checksum or do you investigate and make sure this is expected?

**Comment by jnm2** [comment]
Closing due to lack of response.

**Comment by gep13** [comment]
@jnm2 this package is now being maintained by @mkevenaar and has a new version available:

https://chocolatey.org/packages/bitvise-ssh-server
