### ISSUE TITLE
IDA package ?

### ISSUE THREAD

**Issue by juju4** [dtgm/chocolatey-packages#248]
Hello,

I saw you had a config file for IDA Free
https://github.com/dtgm/chocolatey-packages/blob/master/manual/ida/ida.nuspec
but I don't see it on chocolatey packages repository.

was it submitted or refused? or not working?

Thanks

**Comment by dtgm** [comment]
It was submitted and rejected because it failed automated testing. Here's the failure log https://gist.github.com/choco-bot/ae299a1a04781a4e21f69561c74a8863

**Comment by juju4** [comment]
Just a download error. They probably filter based on user agent.

**Comment by TakataSanshiro** [comment]
I've submitted one.
https://chocolatey.org/packages/ida-free

**Comment by tunisiano187** [comment]
@gep13 this package is maintained by @TakataSanshiro so i think we can close it.
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for confirming
