### ISSUE TITLE
WinRAR needs checksum

### ISSUE THREAD

**Issue by n1trux** [dtgm/chocolatey-packages#252]

**Comment by dtgm** [comment]
Thanks for logging this. Currently, the pkg installs based on the systems LCID and grabs the associated EXE from http://www.win-rar.com/download.html ... this means there is a different checksum for each EXE provided which makes it a bit trickier to add checksum.

**Comment by sippi90** [comment]
any news on the checksum issue?

**Comment by dtgm** [comment]
The English installer (default) is now supported ➜ https://chocolatey.org/packages/winrar/5.40.0.20161221
