### ISSUE TITLE
IrfanviewView

### ISSUE THREAD

**Issue by bcurran3** [dtgm/chocolatey-packages#257]
I uploaded a new IrfanView package about two weeks ago. Can you turn off auto-updates for it until it's updated to work with the auto updates. (I really need to look into this auto-update stuff!) 
https://chocolatey.org/packages/IrfanView
https://github.com/bcurran3/ChocolateyPackages/tree/master/irfanview

**Comment by gep13** [comment]
@bcurran3 I have turned off the automatic packaging of this package.  Please let me know via an issue if there are any other packages that you have taken over maintenance on.  Thanks
