### ISSUE TITLE
cmder release url incorrect.

### ISSUE THREAD

**Issue by TJSoler** [dtgm/chocolatey-packages#259]
Cmder version 1.3.1 tries to download `https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder.7z` when should be downloading `https://github.com/cmderdev/cmder/releases/download/v1.3.1/cmder.7z`.

The difference is the _v_ in the version.

Also, 1.3.2 has been released with the url `https://github.com/cmderdev/cmder/releases/download/v1.3.2/cmder.7z`

It may have something to do with the repo moving from `https://github.com/bliker/cmder` to `https://github.com/cmderdev/cmder` but I dont really understand what is going on on the `ketarin/cmder.xml`

**Comment by smford22** [comment]
+1 on this this. Thanks!

**Comment by fgrosbellet** [comment]
Same issue here. Thanks!

**Comment by gcormier** [comment]
Love to see this one fixed up!

**Comment by binaryguru** [comment]
It would be great if this was fixed so I can fix my broken installation.

**Comment by dtgm** [comment]
Thanks for logging this issue! 

1.3.1 has been updated in
https://chocolatey.org/packages/cmder/1.3.1.20161216
https://chocolatey.org/packages/cmdermini/1.3.1.20161216

1.3.2 has been added
https://chocolatey.org/packages/cmder/1.3.2
https://chocolatey.org/packages/cmdermini/1.3.2
