### ISSUE TITLE
[keepass-plugin-kpscript] Installation to wrong location

### ISSUE THREAD

**Issue by Kyrodan** [dtgm/chocolatey-packages#260]
`kpscript` is not a "real" plugin. It's a helper/automator for KeePass. 
So this mustn't be placed in the plugins folder. It needs to be placed in KeePasse's Application Folder to work.

**Comment by tunisiano187** [comment]
I'll try to check this issue and update the package this weekend

**Comment by tunisiano187** [comment]
@gep13 , i'm taking this package managment as you can see upper.
I think we can close this issue, i'm keeping it on my git and have updated to match the request.

Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks!
