### ISSUE TITLE
Move TortoiseSvn & TortoiseGit to core team repo

### ISSUE THREAD

**Issue by pascalberger** [dtgm/chocolatey-packages#264]
Would you be interested in moving the TortoiseSvn and TortoiseGit packages to the [Chocolatey Community Core Team Packages repo](https://github.com/chocolatey/chocolatey-coreteampackages)? 

Since they are both GPL licensed I would like to change them to embedded packages and at the same time I could also do the migration to the Core Team repo if you are interested.

**Comment by dtgm** [comment]
Sure. Let me know when completed so I may disable my instance.

**Comment by pascalberger** [comment]
OK, will create pull requests

**Comment by pascalberger** [comment]
Pull requests are here #265 & #267
