### ISSUE TITLE
DDU updates

### ISSUE THREAD

**Issue by welwood08** [dtgm/chocolatey-packages#266]
Hi, I understand this is supposed to be an automatic package but I'm not sure how automatic it is considering this is the second time in the last few months I've made preparations to update graphics drivers and noticed that the choco DDU package is several versions behind the latest DDU release.

I'm guessing it's the ketarin stage that's failing to detect a new version when it's posted on the DDU forum? (I'd help if I knew anything about ketarin).

**Comment by dtgm** [comment]
Thanks for reporting! Fixed.

https://chocolatey.org/packages/ddu/17.0.4.1

**Comment by welwood08** [comment]
Excellent! Cheers for the speedy resolution.
