### ISSUE TITLE
Add package parameter to add GUI programs to the Start Menu

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#27]

**Comment by dtgm** [comment]
Manually reviewed programs:

https://chocolatey.org/packages/siteshoter/1.42
https://chocolatey.org/packages/myuninst/1.76
https://chocolatey.org/packages/installedcodec/1.30
https://chocolatey.org/packages/locate32/3.1.11.7100
https://chocolatey.org/packages/aaclr/1.0.2

**Comment by tunisiano187** [comment]
@gep13 i think this one can be closed, the software aren't updated anymore and the total use is at 800 downloads average.

**Comment by gep13** [comment]
@tunisiano187 makes sense to me.
