### ISSUE TITLE
Blink 3.0 not auto released

### ISSUE THREAD

**Issue by Moredread** [dtgm/chocolatey-packages#270]
3.0.0 was released, but not detected by the auto build script it seems. Also install of the older version doesn't work anymore.

**Comment by Moredread** [comment]
I stumbled over that issue again. :p Had you a look at what needs to be done?

**Comment by tunisiano187** [comment]
Hello,
I'm slowly taking these packages, i'm tring to update it, i'll keep you in touch

**Comment by tunisiano187** [comment]
OK, i'll ask to be maintainer and push it asap

**Comment by tunisiano187** [comment]
Added in my git, 
waiting to be maintainer, and i'll push it
Related to #529 and https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/blink

@gep13 , you can close this one.
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks
