### ISSUE TITLE
State how new version can be reported

### ISSUE THREAD

**Issue by koppor** [dtgm/chocolatey-packages#272]
The README.md states fine how the packaging process works, but there is no hint how can I report a new version or whether this is needed at all.

I am using [KeePass](http://keepass.info/), which released a new version 5 days ago. I wonder why the automatic scripts in this repository did not detect it and update KeePass on cholatey automatically.

**Comment by dtgm** [comment]
> The README.md states fine how the packaging process works, but there is no hint how can I report a new version or whether this is needed at all.

Any or all of the following will get to me, some sooner than others: 
Github issue: https://github.com/dtgm/chocolatey-packages/issues/new
Disqus comment on galley page: https://chocolatey.org/packages/keepass#discussion
Send a message via gallery page: https://chocolatey.org/packages/keepass/ContactOwners

>I am using KeePass, which released a new version 5 days ago. I wonder why the automatic scripts in this repository did not detect it and update KeePass on cholatey automatically.

Thanks for letting me know. I reran the scripts and 2.35 was picked up fine. Not sure why there was that hiccup. 2.35 should be approved shortly https://chocolatey.org/packages/keepass/2.35

**Comment by dtgm** [comment]
@koppor fyi

[2.35](https://chocolatey.org/packages/keepass/2.35) has passed automated testing and been approved

`cup keepass -y`
