### ISSUE TITLE
Rarlab updated Winrar download URLs

### ISSUE THREAD

**Issue by lukesodre** [dtgm/chocolatey-packages#273]
I´ve been trying to download the Brazilian Portuguese version

But for my surprise the URL of Rarlab was offline
Apparently they just remove the 0 from of the version name
so the URL that was http://www.rarlab.com/rar/winrar-x64-540br.exe
became http://www.rarlab.com/rar/winrar-x64-540pt.exe

(the same happens for de x86 version)

I don´t know if they just changed just these URL, or for the other languages too
I just verified the English version and it´s the old version 

But know I had to change manually and build the package

**Comment by dtgm** [comment]
Thanks for letting me know. Since every other URL uses 3 digits, I would guess this is a mistake on their end. Could you reach out to them at http://www.rarlab.com/feedback.htm and let me know if you hear back?

**Comment by tunisiano187** [comment]
@gep13 , this package is now maintained by @mkevenaar

**Comment by gep13** [comment]
@tunisiano187 thanks!
