### ISSUE TITLE
MultiBit HD 0.5.0 is out

### ISSUE THREAD

**Issue by koppor** [dtgm/chocolatey-packages#275]
According to https://github.com/keepkey/multibit-hd/releases, MultiBit HD 0.5.0 is the latest version. [Chocolatey offers 0.3.0](https://chocolatey.org/packages?q=multibit)

**Comment by tunisiano187** [comment]
I've prepared the updating package, i'll try to keep it up-to-date, asap

**Comment by tunisiano187** [comment]
PR : #536 
New git location : https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/multibit-hd

**Comment by tunisiano187** [comment]
@gep13 , you can close this issue, i'm now taking it.
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for doing this
