### ISSUE TITLE
fastcopy.portable was broken

### ISSUE THREAD

**Issue by d3m3vilurr** [dtgm/chocolatey-packages#276]
https://github.com/dtgm/chocolatey-packages/blob/1a5c81f/automatic/_output/fastcopy.portable/3.27/tools/chocolateyInstall.ps1

script was generated wrong.

should be
```
$url = 'http://ftp.vector.co.jp/68/40/2323/FastCopy327.zip'
$checksum = '8542ef9320a5e7c9f9622e8d83c6abad52d355e7add91a313b335f4ef6ac8c98'
$url64 = 'http://ftp.vector.co.jp/68/40/2323/FastCopy327_x64.zip'
$checksum64 = '3de53dabf2df8ae2acfea7d984be4ada89d8e3a2dcb62c1bf6d509285b0a43df'
```

**Comment by dtgm** [comment]
Thanks, fixed.

https://chocolatey.org/packages/fastcopy.portable/3.27.0.20170206
