### ISSUE TITLE
[mariadb] Optional service installation

### ISSUE THREAD

**Issue by uiii** [dtgm/chocolatey-packages#279]
Could you please make the service creation optional? I'm using manually created database instances and don't want to run the service at all. Thanks

**Comment by uiii** [comment]
This is still relevant for me, could you please look at this?

**Comment by tunisiano187** [comment]
mkevenaar is now maintaining the package, so this is not related to this repository anymore.

**Comment by gep13** [comment]
@tunisiano187 thank you
