### ISSUE TITLE
sqllitebrowser missed last two releases

### ISSUE THREAD

**Issue by tet3** [dtgm/chocolatey-packages#280]
Both 3.9.0 and 3.9.1 for sqlitebrowser (DB Browser for SQLite) have been released since the 2/13/2016 release update of the 3.8.0.2 version of the choclatey package. 

sqlitebrowser releases: https://github.com/sqlitebrowser/sqlitebrowser/releases
last choclatey update: https://chocolatey.org/packages/sqlitebrowser/3.8.0.2

I note that the 3.8.0 release had some hiccups, and that the BOM fix and a couple of nuspec fixes have been made to that package in this repo, but don't know enough about the inner workings to say whether that's related.

**Comment by dtgm** [comment]
Thanks for reporting!
Fixed
https://chocolatey.org/packages/sqlitebrowser/3.9.1
