### ISSUE TITLE
avgantivirusfree failing to install/not auto-updating

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#287]
https://chocolatey.org/packages/avgantivirusfree/15.0.6140

https://gist.github.com/fb7357f72f4294e94422d4ec6f28ed9d

**Comment by tunisiano187** [comment]
@gep13 , this package has been took by @thilas
So the Issue can be closed.
Thank you
Have a nice day

**Comment by gep13** [comment]
@tunisiano187 thanks for letting me know!
