### ISSUE TITLE
awscli fails to install if already installed outside of choco

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#288]
>I'm getting this error if awscli is already installed but done outside of chocolately:
>
>Installing awscli...
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "E:\BuildAgent02\temp\buildTmp\chocolatey\awscli\1.11.54\AWSCLI64-1.11.54.msi" /quiet /qn /norestart ] was not successful. Exit code was '1603'. See log for possible error messages.
>
>Is there any way to have it not fail if it's already installed?

Reported at https://chocolatey.org/packages/awscli#comment-3174689284

**Comment by tunisiano187** [comment]
@gep13 , you can close this one, jctmedia is the current maintainer
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for confirming
