### ISSUE TITLE
broken fastcopy.portable 3.30

### ISSUE THREAD

**Issue by d3m3vilurr** [dtgm/chocolatey-packages#293]
[autogenerated result](https://github.com/dtgm/chocolatey-packages/blob/2039ac3/automatic/_output/fastcopy.portable/3.30/tools/chocolateyInstall.ps1
) used 2.27 set.

```
url = http://ftp.vector.co.jp/68/61/2323/FastCopy330.zip
checksum = c67bd82f9847d759b1fe114934ca724ead7f49a115764dff5473437a2bf5e926
url64 = http://ftp.vector.co.jp/68/61/2323/FastCopy330_x64.zip
checksum64 = b66b8987d52d3d1a2cfad881f435d8d6cef48a9b72295ab2b2447b7550eec842
```
here is right values.

Related: #276

**Comment by d3m3vilurr** [comment]
@dtgm can you check this issue?

**Comment by dtgm** [comment]
@d3m3vilurr thanks

fixed in https://chocolatey.org/packages/fastcopy.portable/3.30.0.20170422
