### ISSUE TITLE
winscp 5.9.4 installation fails behind proxy

### ISSUE THREAD

**Issue by chenkins** [dtgm/chocolatey-packages#294]
Failure at https://github.com/dtgm/chocolatey-packages/blob/master/automatic/_output/winscp.install/5.9.4/tools/chocolateyInstall.ps1#L38 :
```
Installing winscp.install...
winscp.install has been installed.
ERROR: Exception calling "DownloadString" with "1" argument(s): "The remote serv
er returned an error: (407) Proxy Authentication Required."
The install of winscp.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winscp.install\tools\chocolat
eyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - winscp.install (exited -1) - Error while running 'C:\ProgramData\chocolatey\l
ib\winscp.install\tools\chocolateyInstall.ps1'.
 See log for details.
```
The variables according to https://github.com/chocolatey/choco/wiki/Proxy-Settings-for-Chocolatey are set (http_proxy etc. and chocolatey-specific chocolateyProxyLocation etc.), but are not evaluated. Something as in https://chocolatey.org/install.ps1 is probably missing?

**Comment by dtgm** [comment]
@chenkins Could you please test this new version and let me know if it works for you?

https://chocolatey.org/packages/winscp.install/5.9.4.20170323

**Comment by chenkins** [comment]
@dtgm It works, many thanks for fixing, and even so quickly!
