### ISSUE TITLE
Failure installing partitionwizard 10.0 due to version mismatch

### ISSUE THREAD

**Issue by palonsoro** [dtgm/chocolatey-packages#296]
Download URL for generated package points to: https://www.partitionwizard.com/download/pw10-free.exe

This download URL actually now servers 10.2 installer instead of 10.0 one. So the installation fails, as the hash of 10.0 version seems to be used to check the 10.2 installer.

Important to note that `chocolatey-packages/ketarin/partitionwizard.xml` tries to gather the partitionwizard current version from a non up-to-date place. It tries to get the version from this URL https://www.partitionwizard.com/pad/pwhe.xml and this URL still shows 10.0 as the current version. However, if you do download and manually install the software, you can see it is actually at version 10.2. Thus, this XML might not be a trustworthy source of info anymore (it contains too old metadata).

**Comment by verglor** [comment]
@dtgm Now it is failing again since fix eb9bcdc switched from https://www.partitionwizard.com/pad/pwhe.xml to web scraping but today xml is more actual.
