### ISSUE TITLE
Ability to add CMake to the path

### ISSUE THREAD

**Issue by jnm2** [dtgm/chocolatey-packages#297]
The installer has a checkbox, off by default, to add CMake to the path. I don't see a way to use Chocolatey to get the install I need.

(It would be nice if there was some way to tell Chocolatey that I always want to opt into adding programs to the path by default. I don't know if that is possible, or perhaps everyone will want CMake in the path.)

**Comment by dtgm** [comment]
There is, use `--installargs` to pass properties to MSI
https://github.com/chocolatey/choco/wiki/CommandsReference#how-to-pass-options--switches

`ADD_CMAKE_TO_PATH`
`None` - Do not add CMake to path (default)
`System` - Add CMake to system PATH for __all users__
`User` - Add CMake to system PATH for __current user__

`DESKTOP_SHORTCUT_REQUESTED`
`0` = Do not create desktop icon (default)
`1` = Create CMake desktop icon

For example: `choco install cmake --installargs 'ADD_CMAKE_TO_PATH=""User""'`

I'll add it to the nuspec.

**Comment by jnm2** [comment]
I wish it weren't so verbose, but thanks, that's awesome!
