### ISSUE TITLE
Arduino Autoupdates Not Appearing at Chocolatey.org

### ISSUE THREAD

**Issue by davidski** [dtgm/chocolatey-packages#298]
The current version of the Ardunio package on Chocolatey is from late 2015. There are many (6+) newer auto-update versions generated at https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/arduino, but none of these look to be getting to Chocolatey. What do we need to fix to get these newer versions pushed out for review and publication?

**Comment by tunisiano187** [comment]
@gep13 , this one can be closed, it's maintained by @jctmedia
Thanks

**Comment by gep13** [comment]
@tunisiano187 thanks for confirming!
