### ISSUE TITLE
Mongodb should use ssl packages

### ISSUE THREAD

**Issue by nskaggs** [dtgm/chocolatey-packages#305]
Update the URL to grab mongodb-win32-x86_64-2008plus-ssl. This works for 64-bit anyway; I couldn't find a 32-bit ssl package.

ala;
$url64 = 'http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.2.14.zip'
$checksum64 = '229ba40277329e5bd8a9ce25b2a4002be5d40b7f92ec6612e59293b4fe0fa924'
$checksumType64 = 'sha256'

**Comment by dtgm** [comment]
@nskaggs thanks for reporting this.
