### ISSUE TITLE
Bginfo checksum

### ISSUE THREAD

**Issue by dan-wittenberg** [dtgm/chocolatey-packages#306]
Looks like a newer version of bginfo is available so the checksum no longer matches the package, could this be updated at some point so it starts working again?

Dan

**Comment by dtgm** [comment]
Updated to [4.22.20170623](https://chocolatey.org/packages/bginfo/4.22.20170623) thanks to @flcdrg

**Comment by flcdrg** [comment]
And another version of 4.22 as of 30th June https://chocolatey.org/packages/bginfo/4.22.20170630 :-(
