### ISSUE TITLE
Deprecate nunit package

### ISSUE THREAD

**Issue by CharliePoole** [dtgm/chocolatey-packages#310]
NUnit no longer produces an equivalent package to the old `msi` or `zip`, which was created through 3.4.

The old packages combine library files and executable tools, which we now package separately. We use nuget for the libraries and chocolatey for the executable tools - which, btw, don't reference the libraries. We're using native, standalone packages for executables. One is up and a few more are about to be made available.

I'd like to deprecate the old package. I can create and upload a package to deprecate nunit on chocolatey, but you'll probably want to remove it here as well, just for tidiness. 😄

**Comment by CharliePoole** [comment]
@gep13 @ChrisMaddock I'm not familiar with the structure of this repo or the process of generating packages automatically. However, it looks to me as if changes are needed (1) to remove nunit from the automatic packages and (2) to create a one-time manual nuspec that deprecates the package and points to our nunit-consolerunner package, which is the closest in functionality.

@gel13 Does that make sense? Would you be willing to do (1)? I can do a PR for (2) in that case.

**Comment by CharliePoole** [comment]
@gep13 As I think about it, it may be hard to separte my steps (1) and (2). Maybe I should just provide what you need to set up the one-time manual entry that deprecates the package and points people to the right place. Either way is OK with me.

**Comment by gep13** [comment]
The process that should be followed for these packages is documented here:

https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package

**Comment by gep13** [comment]
@CharliePoole this work has now been completed:

* https://chocolatey.org/packages/nunit
* https://chocolatey.org/packages/nunit.install
* https://chocolatey.org/packages/nunit.portable

**Comment by CharliePoole** [comment]
Thanks!
