### ISSUE TITLE
Telegram package is broken

### ISSUE THREAD

**Issue by NicoHaase** [dtgm/chocolatey-packages#311]
On my system, both telegram and telegram.install are installed. For telegram.install, you've provided an update to version 1.1.7 three weeks ago, but this is not installable, as the latest version of the telegram package has a hard dependency on telegram.install in version 1.0.29

**Comment by dtgm** [comment]
Thanks for letting me know. Fixed.
https://chocolatey.org/packages/telegram/1.1.7
