### ISSUE TITLE
Modify default icon size to 256px for SVG

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#32]
**max**
- [ ] encryptr
- [ ] peerunity

**1024px**
- [ ] bitcoin

**??? rect**
- [ ] wavpack

**512px**
- [ ] peazip
- [ ] genymotion
- [ ] twisted
- [ ] avg
- [ ] kaspersky
- [ ] softwareinformer
- [ ] duplicati
- [ ] mediainfo
- [ ] bitmessage
- [ ] keepass-plugin-1p2keepass
- [ ] trillian
- [ ] hugin
- [ ] hp
- [ ] lyx
- [ ] lmms
- [ ] fritzing
- [ ] xonotic

**384px**
- [ ] cyberduck
- [ ] pandabank
- [ ] opencodecs
- [ ] namecoin
- [ ] opustools

**Comment by tunisiano187** [comment]
## max

- [ ]  encryptr
- [ ]  peerunity
## 1024px

- [ ]  bitcoin
## ??? rect

- [ ] wavpack
## 512px

- [ ] peazip
- [ ] genymotion
- [ ] twisted
- [ ] avg
- [ ] kaspersky
- [ ] softwareinformer
- [ ] duplicati
- [ ] mediainfo
- [ ] bitmessage
- [ ] keepass-plugin-1p2keepass
- [ ] trillian
- [ ] hugin
- [ ] hp
- [ ] lyx
- [ ] lmms
- [ ] fritzing
- [ ] xonotic
## 384px

- [ ] cyberduck
- [ ] pandabank
- [ ] opencodecs
- [ ] namecoin
- [ ] opustools

**Comment by gep13** [comment]
Being honest, this is unlikely to ever get done, so going to close this out.
