### ISSUE TITLE
"CMake" package is not at the same version as "CMake (Install)" and "CMake (Portable)" packages

### ISSUE THREAD

**Issue by i-give-up** [dtgm/chocolatey-packages#325]
At the time of writing, [CMake](https://chocolatey.org/packages/cmake) is at version 3.9.1 whereas [CMake (Install)](https://chocolatey.org/packages/cmake.install) and [CMake (Portable)](https://chocolatey.org/packages/cmake.portable) are both at version 3.9.4. 

This causes error when trying to upgrade either the .install or .portable package

``` text
Updating 'cmake.install 3.9.1' to 'cmake.install 3.9.4' failed. Unable to find
a version of 'cmake' that is compatible with 'cmake.install 3.9.4'
```

I see similar comments on CMake package's page linked above.

**Comment by cenit** [comment]
the problem is still open unfortunately. And cmake.install is also outdated now, breaking my vcpkg toolchain.

**Comment by AdmiringWorm** [comment]
The cmake packages is now located in the core team packages repository: https://github.com/chocolatey/chocolatey-coreteampackages

as such, this issue can be closed

/cc @gep13

**Comment by gep13** [comment]
@AdmiringWorm thanks for the heads up!
