### ISSUE TITLE
handebrake.install URL format has changed

### ISSUE THREAD

**Issue by fbis251** [dtgm/chocolatey-packages#326]
Handbrake has changed their download URL from
`https://handbrake.fr/rotation.php?file=HandBrake-1.0.7-x86_64-Win_GUI.exe`
to
`https://handbrake.fr/mirror/HandBrake-1.0.7-x86_64-Win_GUI.exe`

**Comment by gep13** [comment]
@dtgm are you in a position to look at this one?

It was recently added to the RFM issues list:

https://github.com/chocolatey/chocolatey-package-requests/issues/297

Thanks!

**Comment by tunisiano187** [comment]
@jctmedia is the maintainer of the package.
This issue can be closed.
Thanks @gep13

**Comment by gep13** [comment]
@tunisiano187 thanks for confirming.
