### ISSUE TITLE
keepass.install fails upgrade if KeePass is running

### ISSUE THREAD

**Issue by bcurran3** [dtgm/chocolatey-packages#329]
Upgrade fails but choco believes it passes using keepass virtual package.

STATUS: keepass v2.36 installed

-------------------
C:\WINDOWS\system32>choco upgrade keepass -force
Chocolatey v0.10.8 Professional
Upgrading the following packages:
keepass
By upgrading you accept licenses for the packages.
keepass v2.37 is the latest version available based on your source(s).
Progress: Downloading keepass.install 2.37... 100%
Progress: Downloading keepass 2.37... 100%

keepass.install v2.37 (forced) [Approved]
keepass.install package files upgrade completed. Performing other installation steps.
Downloading keepass.install
  from 'https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.37/KeePass-2.37-Setup.exe/download'
Using download CDN cache instead of original url.
Progress: 100% - Completed download of 'KeePass-2.37-Setup.exe' (3.08 MB).
Download of 'KeePass-2.37-Setup.exe' (3.08 MB) completed.
Virus check: 0/66 scan engines flagged this assembly.
 Due to possible false positives we fail at 4 minimum positives.
 Virus scan engines indicate this file is probably safe. For details see
  https://www.virustotal.com/file/3eb75f0d942704693110859e97b66b8e5245398dde7e2ccd82ab0abcc5d73b36/analysis/
Hashes match.
Installing KeePass-2.37-Setup.exe...
ERROR:
Running ['C:\Users\bcurran\AppData\Local\Temp\chocolatey\keepass.install\2.37\KeePass-2.37-Setup.exe'  /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-] was not successful.
 Exit code was '1' See log for possible error messages.
**The upgrade of keepass.install was NOT successful.**
Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.

keepass v2.37 (forced) [Approved]
keepass package files upgrade completed. Performing other installation steps.
 **The upgrade of keepass was successful.**
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey upgraded 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - keepass.install (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\keepass.install\tools\chocolateyInstall.ps1'.
 See log for details.

C:\WINDOWS\system32>clist keepass -l
Chocolatey v0.10.8 Professional
keepass 2.37
1 packages installed.

-----------------------

STATUS: keepass v2.36 still installed

**Comment by bcurran3** [comment]
Closing as this has been re-addressed here: https://github.com/pauby/ChocoPackages/issues/13 but won't be fixed.

**Comment by gep13** [comment]
@bcurran3 I have deleted the related files from this repository, as they are being maintained elsewhere.

@bcurran3 reading through that issue that you linked to, it does seem as though @pauby would accept a PR to correct the issue, if a solution that covers all the scenarios can be achieved.  If you are in a position to help out, then I would suggest submitting a PR.
