### ISSUE TITLE
SUMo Is Out Of Date

### ISSUE THREAD

**Issue by zero77** [dtgm/chocolatey-packages#330]
There are several newer version out now, and it is regularly updated.
Please can you auto update SUMo, Thanks

**Comment by zero77** [comment]
Sandboxie is still out of date, can you please consider moving it to the main chocolatey repository.
Thanks
www.github.com/chocolatey/chocolatey-coreteampackages

**Comment by gep13** [comment]
@zero77 that is certainly something that I "could" do, it is just a case of finding the time.  That repository uses AU to do the automatic updating, where as this one uses Ketarin.  So there would be some work involved in converting it over.  Not impossible, but would need some work.

**Comment by zero77** [comment]
Yes I see your point, though thanks for considering it.

**Comment by bcurran3** [comment]
I think the package is current again.

**Comment by gep13** [comment]
@bcurran3 thank you for confirming.

**Comment by zero77** [comment]
@bcurran3 
Thanks
