### ISSUE TITLE
Sandboxie Is Out Of Date

### ISSUE THREAD

**Issue by zero77** [dtgm/chocolatey-packages#331]
There is a newer version out now.

**Comment by zero77** [comment]
@gep13 
Sandboxie is still out of date, can you please consider moving it to the main chocolatey repository.
Thanks
www.github.com/chocolatey/chocolatey-coreteampackages

**Comment by gep13** [comment]
@zero77 that is certainly something that I "could" do, it is just a case of finding the time.  That repository uses AU to do the automatic updating, where as this one uses Ketarin.  So there would be some work involved in converting it over.  Not impossible, but would need some work.
