### ISSUE TITLE
[ninja] update to 1.8.2

### ISSUE THREAD

**Issue by cenit** [dtgm/chocolatey-packages#333]
ninja is still 1.7.2, while 1.8.2 is out now for almost 2 months. On the discuss thread in the package webpage it has already been stated, I am opening an issue also here hoping that it can be noticed. I'd like to contribute and update some packages, but it seems so complicated to start and submit a new revision...

**Comment by gep13** [comment]
@cenit am I right in saying that this issue has been moved elsewhere?  As I don't think this package is kept in this repository?

**Comment by cenit** [comment]
you are perfectly right. Sorry for having opened here first of all!
The new issue is here https://github.com/chocolatey/chocolatey-package-requests/issues/259
I will try to contribute asap with the fix

**Comment by gep13** [comment]
Not a problem at all, just wanted to check 😄
