### ISSUE TITLE
smartmontools is outdated

### ISSUE THREAD

**Issue by seeker** [dtgm/chocolatey-packages#341]
- latest version number
6.6-1
- release date
2017-11-05
- URL to the install binary
https://sourceforge.net/projects/smartmontools/files/smartmontools/6.6/smartmontools-6.6-1.win32-setup.exe

**Comment by dtgm** [comment]
Updated in https://github.com/dtgm/chocolatey-packages/commit/5320e16271fb80749eb9ed5a99abb7c9d68e906c#diff-78dd01c9e5545b2f2312165934819145

https://chocolatey.org/packages/smartmontools/6.6.1
