### ISSUE TITLE
(datacrow) Find alternative download URL

### ISSUE THREAD

**Issue by gep13** [dtgm/chocolatey-packages#349]
Currently it is using FossHub which is no longer allowed.

**Comment by Gedankenleser** [comment]
Filehippo has a installer zip
https://filehippo.com/de/download_datacrow_windows/
Why is fosshub not allowed? Is Filehippo ok?

**Comment by gep13** [comment]
@Gedankenleser FossHub have asked that Chocolatey packages not use there hosting site as a source for packages.  We would either need to use another URL, FileHippo would be fine, or if the license of datacrow allows, look to making it an embedded package.

**Comment by Gedankenleser** [comment]
Thx for the quick answer. Maybe i will try to fix it later.

**Comment by gep13** [comment]
@Gedankenleser that would be great! Thank you!

**Comment by tunisiano187** [comment]
Hi, i've made the package on my git, without fosshub, i'll push a PR when i'm added as maintainer.
Have a nice day.

**Comment by gep13** [comment]
As per this PR: https://github.com/dtgm/chocolatey-packages/pull/642 this package is now being maintained by @tunisiano187
