### ISSUE TITLE
Conform uninstall scripts to default template

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#35]
Implement improvements and conform for consistency and ease of maintainability to chocolateyUninstall.ps1 files based on https://github.com/chocolatey/choco/issues/366

**Comment by tunisiano187** [comment]
@gep13 , this one can be closed too.
it's just a link to the issue.
Even if i'll keep that in mind ;-)

Thank you

**Comment by gep13** [comment]
@tunisiano187 sounds good.
