### ISSUE TITLE
(fossil) Update to latest version

### ISSUE THREAD

**Issue by ebugusey** [dtgm/chocolatey-packages#361]
On choco repository it's up to 1.35, but latest version is 2.5.

**Comment by zilti** [comment]
Seconded. It's annoying to have an ancient version of fossil on choco.

**Comment by tunisiano187** [comment]
@gep13 , it's maintained by another now.
So you can close it.
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for confirming
