### ISSUE TITLE
Package Updates by @dtgm

### ISSUE THREAD

**Issue by Gedankenleser** [dtgm/chocolatey-packages#362]
hello ist this respository still maintained by @dtgm ?
Since a long time no commits were made by him. When i unerstand the concept of this repot correct, if no changes made bei him no updates go to to the choco respository. Please say if i am wrong. 
Have a nice day.

**Comment by gep13** [comment]
@Gedankenleser what you have said is correct.  If no updates are made to this repository, then it is unlikely that any changes will be pushed to the upstream Chocolatey package on chocolatey.org.  @dtgm used to be very active, and created a number of packages in this repository, but he doesn't seem to have the same time available to maintain these packages.  I have been given commit rights to this repository, so I will be able to make any changes if someone were to create Pull Requests, however, it is unlikely that I will have the available bandwidth to actively fix packages myself.

You will have noticed that some packages have been migrated from this repository to the Core Team Packages repository, and other packages which @dtgm was maintaining have been taken over by other maintainers.

I hope this answers your questions.
