### ISSUE TITLE
FEATURE REQUEST: https://chocolatey.org/packages/dumo

### ISSUE THREAD

**Issue by bcurran3** [dtgm/chocolatey-packages#365]
After the package installs, the DUMo program runs. 
Please quit the program post install.

**Comment by gep13** [comment]
@bcurran3 are you in a position to provide a PR for fixing this?

**Comment by AdmiringWorm** [comment]
@bcurran3 I've taken over the maintenance of dumo, if you still see this issue, then please open up an issue over at https://github.com/AdmiringWorm/chocolatey-packages/issues

**Comment by bcurran3** [comment]
Thanks for the update.

I just installed it.

Dumo does run during install, but it also quits afterwards.

![image](https://user-images.githubusercontent.com/14026600/51415502-ea994380-1b2a-11e9-9763-e03c0c271c5f.png)

![image](https://user-images.githubusercontent.com/14026600/51415534-fd137d00-1b2a-11e9-8026-cc77136e6d4b.png)


I'll call is a success.

Closing.

**Comment by AdmiringWorm** [comment]
@bcurran3 that's good to hear.
I had to use autohotkey to close it (which I'm not really familiar with).

**Comment by bcurran3** [comment]
I didn't look at the scripts, but I'd recommend an update to hit enter on that "Checking..." window and then you'd be able to close the program faster without having to wait for it to go through checking all the drivers (causes a lag). Low priority for sure, but it would better it.

Personally I prefer killing the process, but I know others aren't fond of the idea.

I'm not sure if you wanted to inherit this package or not. I do a bunch of driver packages and this is helpful for me to keep tabs on new versions for them. If you're just being nice and don't really want the package, I volunteer to take it off your hands. If not, no worries, I don't need more packages to maintain!   
(I do do the SuMo package now and routinely see the DuMo version and download button though...that's why taking on this wouldn't be a big deal.)

**Comment by AdmiringWorm** [comment]
> I didn't look at the scripts, but I'd recommend an update to hit enter on that "Checking..." window and then you'd be able to close the program faster without having to wait for it to go through checking all the drivers (causes a lag). Low priority for sure, but it would better it.

I did actually add that, but I see now that I have a typo in the autohotkey script.
Tracking it here: https://github.com/AdmiringWorm/chocolatey-packages/issues/44 (yes, I reused your screenshot 😄)

> Personally I prefer killing the process, but I know others aren't fond of the idea.

I did that initially, but it wouldn't work as it should. (Can't remember now why though).

> I'm not sure if you wanted to inherit this package or not. I do a bunch of driver packages and this is helpful for me to keep tabs on new versions for them. If you're just being nice and don't really want the package, I volunteer to take it off your hands. If not, no worries, I don't need more packages to maintain!
(I do do the SuMo package now and routinely see the DuMo version and download button though...that's why taking on this wouldn't be a big deal.)

I already invested the time to change the package to my own standards, and adding it to my automatic update schedule (every 6th hour). So for now, I'd like to continue maintaining the package. I may take you up on the offer in the future though.

**Comment by bcurran3** [comment]
No problem. Thanks for giving the package such attention.

Killing the task "should" be easy and less work than AHK though!

Feel free to reuse some functions from https://chocolatey.org/packages/chocolatey-misc-helpers.extension if you like.
