### ISSUE TITLE
FEATURE REQUEST: https://chocolatey.org/packages/sumo

### ISSUE THREAD

**Issue by bcurran3** [dtgm/chocolatey-packages#366]
After the package installs, the SUMo program runs. 
Please quit the program post install.

**Comment by gep13** [comment]
@bcurran3 are you in a position to provide a PR for fixing this?

**Comment by bcurran3** [comment]
pre-dupe of https://github.com/dtgm/chocolatey-packages/issues/411

Closing as request is now irrelevant.
