### ISSUE TITLE
“sqlitebrowser” is out of date

### ISSUE THREAD

**Issue by franklinyu** [dtgm/chocolatey-packages#375]
It has been out of date since last September. I didn’t submit pull request because I’m not sure how AU works.

**Comment by gep13** [comment]
@franklinyu just to be clear, this repository is not using AU, it is using ketarin.

**Comment by franklinyu** [comment]
See also chocolatey/chocolatey-package-requests#255.

**Comment by dtgm** [comment]
@franklinyu Thanks!
Built in commit 9610adef1757285d586a6c45d88f1c8c679a0c85
Updated chocolatey.org https://chocolatey.org/packages/sqlitebrowser/3.10.1

**Comment by franklinyu** [comment]
@dtgm If you would like to keep maintain this package, then I think chocolatey/chocolatey-package-requests#255 should be closed.
