### ISSUE TITLE
“ilspy” is out of date

### ISSUE THREAD

**Issue by franklinyu** [dtgm/chocolatey-packages#377]
Latest release is [3.0.1](https://github.com/icsharpcode/ILSpy/releases/tag/v3.0.1). According to the package page, maintainers are @alanstevens @jongalloway?

**Comment by giggio** [comment]
I just sent them a message through the Chocolatey site. I hope they update this soon.

**Comment by giggio** [comment]
Created PR #378 to solve this. Package is tested and working.

**Comment by gep13** [comment]
@giggio I am going to close this issue, as it looks like @majkinetor is going to take care of this.

**Comment by franklinyu** [comment]
@gep13 Thank you. Shall I track chocolatey/chocolatey-package-requests#271 for updates? Or anything else?

**Comment by gep13** [comment]
@franklinyu @jongalloway yes, I would suggest keeping an eye on that issue for updates.  Once everything is done, I will remove the files from this repository, to make it clear that it is no longer being maintained here.
