### ISSUE TITLE
Add new metadata field in anticipation of chocolatey.org

### ISSUE THREAD

**Issue by alexchandel** [dtgm/chocolatey-packages#38]
#18 mentions three useful fields,
- [ ] replaces
- [ ] provides
- [ ] conflicts

which were not added at the time, because chocolatey.org presently ignores them. However, many packages have infrequent release cycles, and preemptive adoption will ease the transition to virtual packages by guaranteeing the existence of some infrastructure, so I propose these fields, particularly `provides`, be added now.

This is applicable to packages like `cmake.portable`, `handbrake.portable`, and others, as well as the corresponding `.install` packages.

**Comment by gep13** [comment]
I don't think that there is anything left to do on this issue, so I am going to go ahead and close it.
