### ISSUE TITLE
bug: GUI pop-up when upgrading sqlitebrowser

### ISSUE THREAD

**Issue by FranklinYu** [dtgm/chocolatey-packages#385]
When upgrading `sqlitebrowser` from 3.10.0 to 3.10.1, an interactive pop-up appeared, guiding me through removing old version. It is fine for me, but I believe Chocolatey overall would expect GUI-free.

**Comment by franklinyu** [comment]
Uninstallation is also not silent.

**Comment by tunisiano187** [comment]
@gep13, this can be closed, @mkevenaar is now the maintainer

**Comment by gep13** [comment]
@tunisiano187 thanks for letting me know!
