### ISSUE TITLE
RetroShare releases has changed location

### ISSUE THREAD

**Issue by G10h4ck** [dtgm/chocolatey-packages#386]
Hi!

Thanks you for publishing retroshare on chocolatey, I have seen that the last version available there is the 0.6.0 that is very old, discussing on chocolatey chat it seems it is because we changed the location of where the releases are published, we don't distribute retroshare via sourceforge anymore, we do it via github, would you be so kind to update the chocolatey package?

https://github.com/RetroShare/RetroShare/releases/

Cheers!

**Comment by felisucoibi** [comment]
+1

**Comment by gep13** [comment]
@tunisiano187 Thanks for the PR related to this one.
