### ISSUE TITLE
[keepass-plugin-keeagent] Update to 0.10.1

### ISSUE THREAD

**Issue by coldacid** [dtgm/chocolatey-packages#389]
0.8.1 does not work with Keepass 2.39 or newer due to plugin API changes in that version of Keepass. As such everyone who has upgraded Keepass today cannot use the version of Keeagent available through Chocolatey. We need an immediate package update to 0.10.1 released approximately three and a half weeks ago.

**Comment by pauby** [comment]
I will [pick this up](https://github.com/chocolatey/chocolatey-package-requests/issues/351).

**Comment by gep13** [comment]
@pauby can you also make a PR into this repo to remove it from the ketarin automation?  Thanks!

**Comment by pauby** [comment]
@gep13 I shall do.

**Comment by hansdg1** [comment]
Hi @pauby, how's the packing going? Any idea when you'll have it up? Thanks

**Comment by pauby** [comment]
@hansdg1 Been incredibly busy. Will get it done next week.

**Comment by pauby** [comment]
@hansdg1 0.10.1 package has now been pushed. @gep13 PR #405 created to remove from here.
