### ISSUE TITLE
Tortoise Hg: Update to version 4.6

### ISSUE THREAD

**Issue by linkp** [dtgm/chocolatey-packages#391]
Latest version number: 4.6
Release date: 2018-05-21
URL to the install binary:

    32-bit: https://bitbucket.org/tortoisehg/files/downloads/tortoisehg-4.6.0-x86.msi
    64-bit: https://bitbucket.org/tortoisehg/files/downloads/tortoisehg-4.6.0-x64.msi

Release notes: https://bitbucket.org/tortoisehg/thg/wiki/ReleaseNotes#!tortoisehg-46

**Comment by Thieum** [comment]
Latest version number: 4.8
Release date: 2018-11-12
URL to the install binary:

32-bit: https://bitbucket.org/tortoisehg/files/downloads/tortoisehg-4.8.0-x86.msi
64-bit: https://bitbucket.org/tortoisehg/files/downloads/tortoisehg-4.8.0-x64.msi
Release notes: https://bitbucket.org/tortoisehg/thg/wiki/ReleaseNotes#!tortoisehg-48
