### ISSUE TITLE
[cmder][cmdermini] Upgrade to 1.3.6

### ISSUE THREAD

**Issue by verglor** [dtgm/chocolatey-packages#395]
Please upgrade to cmder [1.3.6](https://github.com/cmderdev/cmder/releases/tag/v1.3.6)

Is it possible to automatically upgrade package when a new version is released in github ?

**Comment by AdmiringWorm** [comment]
I've taken over the maintenance of these two packages, which are located in my repository here: https://github.com/AdmiringWorm/chocolatey-packages

/CC @gep13

**Comment by AdmiringWorm** [comment]
Oh, they are both automated (checked every 6th hour)

**Comment by gep13** [comment]
@AdmiringWorm thanks for the heads up!
