### ISSUE TITLE
Update UltraVNC to 1.2.1.7

### ISSUE THREAD

**Issue by rgl** [dtgm/chocolatey-packages#396]
Can you please update the UltraVNC package to 1.2.1.7?

**Comment by DJCrashdummy** [comment]
[UltraVNC](https://chocolatey.org/packages/ultravnc) is up to date and this can be closed.

**Comment by tunisiano187** [comment]
@gep13 , This is supported by @mkevenaar .
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for checking
