### ISSUE TITLE
update dupeguru to 4.0.3

### ISSUE THREAD

**Issue by jacktose** [dtgm/chocolatey-packages#397]
[Current chocolatey package](https://chocolatey.org/packages/dupeguru) is on 3.9.1, which is years old.
[Current version is 4.0.3.](https://dupeguru.voltaicideas.net/)

**Comment by jacktose** [comment]
Oh, the project moved.
https://www.hardcoded.net/dupeguru/ says:
> **This website has moved.** I don't maintain dupeGuru anymore. Andrew Senetar does and dupeGuru's now homepage is https://dupeguru.voltaicideas.net/

So it looks like the metadata will need updating. I don't understand the automation stuff enough, or I'd try.

**Comment by DJCrashdummy** [comment]
according to [chocolatey](https://chocolatey.org/packages/dupeguru) and https://github.com/chocolatey-community/chocolatey-package-requests/issues/516 this can be closed.
