### ISSUE TITLE
CurrPorts update failed

### ISSUE THREAD

**Issue by FranklinYu** [dtgm/chocolatey-packages#401]
Looking at the source of 2.51:

https://github.com/dtgm/chocolatey-packages/blob/master/automatic/_output/cports/2.51/tools/chocolateyInstall.ps1#L3-L6

Compare it with 2.50:

https://github.com/dtgm/chocolatey-packages/blob/master/automatic/_output/cports/2.50/tools/chocolateyInstall.ps1#L3-L6

The `checksum` and `checksum64` is lost.

**Comment by tunisiano187** [comment]
Package ready on my git, will be pushed with that correction and latest version asap.

**Comment by gep13** [comment]
@tunisiano187 thanks
