### ISSUE TITLE
Add /NoService to `mariadb` package

### ISSUE THREAD

**Issue by blackwind** [dtgm/chocolatey-packages#404]
I only need MariaDB running when I'm developing, but this package installs and starts the service on every install and upgrade. Please add the /NoService package parameter.

**Comment by tunisiano187** [comment]
@gep13 , this one is maintained by mkevenaar
#279 , and #403 are also related to MariaDB

**Comment by gep13** [comment]
@tunisiano187 thanks for finding this.  @mkevenaar might be good to look at this in your own repository, if this is still something that is required.
