### ISSUE TITLE
Spark is Outdated

### ISSUE THREAD

**Issue by bzappellini** [dtgm/chocolatey-packages#409]
Spark is Outdated.
latest version number: 2.8.3
release date: January 29, 2017
URL to the install binary: https://igniterealtime.org/downloadServlet?filename=spark/spark_2_8_3.exe

**Comment by tunisiano187** [comment]
@gep13 , this package is mainained by @mkevenaar 
so it can be closed.

**Comment by gep13** [comment]
@tunisiano187 thanks
