### ISSUE TITLE
Telegram package is broken - again

### ISSUE THREAD

**Issue by NicoHaase** [dtgm/chocolatey-packages#410]
As already reported in #311, there has been an update to `telegram.install`, but not an update for `telegram`. This makes it impossible to update `telegram.install`, as `telegram` depends on a specific version of the install package. Is there any way to find a long-term solution for this?

**Comment by sippi90** [comment]
you can close this issue, there is a New maintainer.

**Comment by gep13** [comment]
@sippi90 thank you.

I have removed the files related to the Telegram application from this repository: https://github.com/dtgm/chocolatey-packages/commit/9b7b192a8aaec825b7b2a138d2b789c2660918c7
