### ISSUE TITLE
SUMo - please remove from any automated updates

### ISSUE THREAD

**Issue by bcurran3** [dtgm/chocolatey-packages#411]
I've been added as a maintainer and have pushed the latest version.

**Comment by gep13** [comment]
@bcurran3 are you in a position to do this work via a Pull Request into this repository?  Thanks

**Comment by bcurran3** [comment]
I'm going to have to say no based on not knowing the right method. 

Is it as simple as doing the PR, deleting the files, and then submitting?

It'd be faster if you just delete it. :)

**Comment by gep13** [comment]
>@bcurran3 said....
Is it as simple as doing the PR, deleting the files, and then submitting?

Pretty much.  Have a look at the commit that I just added.

You delete all the packaging files from the automatic folder, the associated file in the ketarin folder.  Leave the icon in place, as that will still be valid for historical packages.
