### ISSUE TITLE
[cmdermini] remove deprecated PS function and change install location

### ISSUE THREAD

**Issue by jansohn** [dtgm/chocolatey-packages#413]
The package currently uses a deprecated Powershell function and installs to `C:\tools`.

    Get-BinRoot is going to be deprecated in v1 and removed in v2. It has been replaced with Get-ToolsLocation (starting with v0.9.10), however many packages no longer require a special separate directory since package folders no longer have versions on them. Some do though and should continue to use Get-ToolsLocation.

IMHO it should not be installed to `C:\tools` but rather like `putty.portable` or `mpv.portable` to its default chocolatey lib directory.

**Comment by AdmiringWorm** [comment]
@gep13 since I've taken over the maintenance of cmdermini (and this function isn't used anymore), maybe time to close this issue

**Comment by jansohn** [comment]
Thanks for taking over the package and fixing the issue!
