### ISSUE TITLE
delete telegram folders

### ISSUE THREAD

**Issue by sippi90** [dtgm/chocolatey-packages#421]
New Maintainer - Please delete the folders telegram / telegram.install & telegram.portable

**Comment by gep13** [comment]
This was done here:

https://github.com/dtgm/chocolatey-packages/commit/9b7b192a8aaec825b7b2a138d2b789c2660918c7

If this happens again, please feel free to raise a PR to remove the files.

**Comment by gep13** [comment]
This was taken care of here: https://github.com/dtgm/chocolatey-packages/commit/9b7b192a8aaec825b7b2a138d2b789c2660918c7
