### ISSUE TITLE
Maintain 'keepass-langfiles'

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#43]
Per [disqus on 22 Aug 2015](http://chocolatey.org/packages/keepass#comment-2208380993)

> updates of this one should be associated with KeePass 2.x language files 
> https://chocolatey.org/packages/keepass-langfiles

**Comment by tunisiano187** [comment]
@gep13 this package is on the coreteampackage 
You can close i think

Thanks

**Comment by gep13** [comment]
@tunisiano187 makes sense to me.
