### ISSUE TITLE
[keepass-plugin-ioprotocolext] Update to 1.16

### ISSUE THREAD

**Issue by pmolensky** [dtgm/chocolatey-packages#439]
latest version number: 1.16
release date: 2018-12-15
URL to the install binary: https://keepass.info/extensions/v2/ioprotocolext/IOProtocolExt-1.16.zip

**Comment by CWempe** [comment]
Looks like this can be closed.

![image](https://user-images.githubusercontent.com/1270359/76153877-31e9e700-60d3-11ea-8064-7a50b32a33f3.png)

**Comment by tunisiano187** [comment]
@gep13 , you can close this request as it's up-to-date

**Comment by gep13** [comment]
@tunisiano187 thanks for looking into this!
