### ISSUE TITLE
claws mail stays at 3.16.0

### ISSUE THREAD

**Issue by TimB87** [dtgm/chocolatey-packages#441]
Hey there,
even though claws mail is reported to be 3.17.0 in choco, I still get 3.16.0 when I open it. Anything you could do about that?
Current release is 3.17.3 from 22. Dec. 2018
https://claws-mail.org/releases.php

Best regards,
Tim

**Comment by TimB87** [comment]
https://github.com/dtgm/chocolatey-packages/issues/362
I guess not :)

**Comment by gep13** [comment]
@TimB87 This particular package has now been taken over by @AdmiringWorm, and a new version has just been released.  So you should hopefully be good to go!

**Comment by TimB87** [comment]
@gep13 Thanks for the heads up! :+1:
