### ISSUE TITLE
Hugin is outdated / hugin.install possibly missing

### ISSUE THREAD

**Issue by Katonka** [dtgm/chocolatey-packages#450]
Hi there,

Hugin is not updating to the latest version. Could it be, that the following package source is missing?
https://github.com/dtgm/chocolatey-packages/tree/master/automatic/hugin.install

Cheers

**Comment by tunisiano187** [comment]
@gep13 , this package is now maintained by @chtof , so this can be closed

**Comment by gep13** [comment]
@tunisiano187 sounds good! I have removed the hugin files from this repository.
