### ISSUE TITLE
'Opus Tools' is outdated

### ISSUE THREAD

**Issue by dimqua** [dtgm/chocolatey-packages#451]
https://chocolatey.org/packages/opus-tools
The latest version is 0.2.

**Comment by tunisiano187** [comment]
I'll try to update it this evening

**Comment by tunisiano187** [comment]
Maintainer request sent

**Comment by tunisiano187** [comment]
Pushed

**Comment by gep13** [comment]
@tunisiano187 thanks, I will go ahead and close out this issue.
