### ISSUE TITLE
Install4j outdated

### ISSUE THREAD

**Issue by lasselindqvist** [dtgm/chocolatey-packages#457]
Install4j outdated. The newest version is 7.0.11. It was released 2019-04-15 (https://www.ej-technologies.com/download/install4j/changelog.html)

https://download-keycdn.ej-technologies.com/install4j/install4j_windows_7_0_11.exe
https://download-keycdn.ej-technologies.com/install4j/install4j_windows-x64_7_0_11.exe

The newest release here is 7.0.4 (https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/install4j, https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/install4j.install, https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/install4j.portable)

**Comment by FranklinYu** [comment]
Have you tried the “contact maintainer” function on the package page?

**Comment by lasselindqvist** [comment]
I'll close this, since there is another package, that provides what is needed (https://chocolatey.org/packages/install4j.install)
