### ISSUE TITLE
keepass-plugin-keeautoexec broken in version 2.4

### ISSUE THREAD

**Issue by donestefan** [dtgm/chocolatey-packages#459]
Hi, the 2.4 version keepass-plugin-keeautoexec is not working.
There is an error message "plugin incompatible with the current KeePass version" when starting keepass. 
Seems like this is caused by your renaming of the downloaded files. To fix the error I needed to rename "keepass-plugin-keeautoexec.dll" back to the original name "KeeAutoExec.dll" (note the uppercase letters). Maybe you should use Subfolders instead of file renaming if you want to separate the multiple plugins from each other.

**Comment by yamlCase** [comment]
I have found this issue as well, hopefully nicksmith53's pull request can be merged if applicable

**Comment by yamlCase** [comment]
Even simpler, the DLL can just be omitted from the install:

https://sourceforge.net/p/keepass/discussion/329220/thread/cd5f34604f/?limit=25#f494

**Comment by tunisiano187** [comment]
@gep13 , you can close this one too as Pauby is maintaining it.
Thank you

**Comment by gep13** [comment]
👍
