### ISSUE TITLE
Argyll Updated 2.1.1 (29th April 2019)

### ISSUE THREAD

**Issue by AeliusSaionji** [dtgm/chocolatey-packages#460]
Hello! The Argyll package is out of date.

**Comment by gep13** [comment]
@AeliusSaionji thank you for reporting this.  Are you in a position to help with getting this package updated?

**Comment by AeliusSaionji** [comment]
Sure- I couldn't tell from your repo, do you use AU?

**Comment by omigeot** [comment]
Hi. What would be needed to get the package updated? AFAICT, there is not much difference between 2.0.1 et 2.1.1, installation-wise, just a different upstream package to get.

**Comment by tunisiano187** [comment]
@gep13 ,you can close this one.
jtcmedia is the current maintainer.

**Comment by gep13** [comment]
@tunisiano187 thanks for confirming.
