### ISSUE TITLE
Generate simple powershell scripts additionally to chocolatey

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dtgm/chocolatey-packages#469]
- for each chocolatey package (when possible) generate script like this `https://github.com/dzmitry-lahoda/powershell-install-silent/blob/master/7zip/19.00.ps1`
- generate file with list of all software, then list for versions
- generate installer scripts like `Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/dzmitry-lahoda/powershell-install-silent/master/7zip/19.00.ps1'))`

So could get `choco` free setup on Windows 10 and Server 2019 for many applications.   

Just for reference https://github.com/dzmitry-lahoda/powershell-install-silent .

Feel free to close issues. It is just idea to look from another perspective.

**Comment by dzmitry-lahoda** [comment]
Nope. Choco won.

**Comment by tunisiano187** [comment]
OK, so can you close it?
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for following up with this.
