### ISSUE TITLE
PSDesiredStateConfiguration URL outdated

### ISSUE THREAD

**Issue by mikehumphrey** [dtgm/chocolatey-packages#47]
The current maintained version of the xPSDesiredStateConfiguration Module is located in a new location on either the master branch of Github or the Powershell Gallery.  
- [Github](https://github.com/PowerShell/xPSDesiredStateConfiguration/tree/master) 
- [PowershellGallery.com](http://www.powershellgallery.com/packages/xPSDesiredStateConfiguration/)

Current Module Version:  3.4.0

**Comment by tunisiano187** [comment]
@gep13 this one isn't part of the repository anymore, but is broken... 
Is it intersting to get it up-to-date ? an install-module and import-module can do the same...

**Comment by tunisiano187** [comment]
Since the package is already existing, i've updated and added it to my own repository and asked the maintainer to add me.

**Comment by gep13** [comment]
@tunisiano187 I will go ahead and close this one out then.

**Comment by tunisiano187** [comment]
@gep13 , i'm maintaining this now.
You can close this one.

Thank you.

**Comment by gep13** [comment]
@tunisiano187 thank you
