### ISSUE TITLE
Electrum is heavily outdated

### ISSUE THREAD

**Issue by DJCrashdummy** [dtgm/chocolatey-packages#474]
**`electrum` 3.3.8** was [release](https://github.com/spesmilo/electrum/releases)d at 2019-07-11 and the **[chocolatey package](https://www.chocolatey.org/packages/electrum) is still at 3.1.2** (2018-03-28), which is pretty bad for such a sensitive pice of software... but even worse, versions <3.3.2 can't connect to it's servers any more due to security reasons of a possible phishing attack: https://github.com/spesmilo/electrum/issues/4968
please update the chocolatey package asap. thank you!

btw: the [`electrum.portable`](https://www.chocolatey.org/packages/electrum.portable) package is up to date.

**Comment by tunisiano187** [comment]
Pushed, will see if everything is OK.

**Comment by tunisiano187** [comment]
@gep13 you can close this one, i'm taking care of it.
Thank you

**Comment by gep13** [comment]
@tunisiano187 perfect, thanks
