### ISSUE TITLE
[keepass-plugin-keeagent] Update to 0.11

### ISSUE THREAD

**Issue by coldacid** [dtgm/chocolatey-packages#475]
KeePass 2.41 does not work with KeeAgent 0.10.1 or older. KeeAgent 0.11 has been out for about a week now. Please update the Chocolatey package.

**Comment by tunisiano187** [comment]
@gep13 , can be closed, it's managed by pauby.
Thank you.

**Comment by gep13** [comment]
@tunisiano187 👍
