### ISSUE TITLE
[keepass-plugin-webautotype] uninstallation does not work

### ISSUE THREAD

**Issue by donestefan** [dtgm/chocolatey-packages#476]
"choco uninstall keepass-plugin-webautotype" throws the following error:

```
ERROR: In C:\ProgramData\chocolatey\lib\keepass-plugin-webautotype\tools\chocolateyUninstall.ps1:56 Zeichen:9
+   } else ($file -gt 1) {
+         ~
Missing statement block after 'else' keyword.

In C:\ProgramData\chocolatey\lib\keepass-plugin-webautotype\tools\chocolateyUninstall.ps1:56 Zeichen:24
+   } else ($file -gt 1) {
+                        ~
Unexpected token '{' in expression or statement.
keepass-plugin-webautotype uninstall not successful.
Error while running 'C:\ProgramData\chocolatey\lib\keepass-plugin-webautotype\tools\chocolateyUninstall.ps1'.
 See log for details.
keepass-plugin-webautotype not uninstalled. An error occurred during uninstall:
 keepass-plugin-webautotype uninstall not successful.
```

**Comment by tunisiano187** [comment]
Removed in PR #525 and corrected in https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/keepass-plugin-webautotype
and requested to be maintainer, so it will be updated asap.

You can close the issue.
Have a nice day.

**Comment by tunisiano187** [comment]
olved in the PR just upper and https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/keepass-plugin-webautotype
Just waiting to be added as maintainer.

Thank you
@gep13 this can be closed too

**Comment by gep13** [comment]
@tunisiano187 thanks for doing this!
