### ISSUE TITLE
Republish dd package with a checksum

### ISSUE THREAD

**Issue by Chirishman** [dtgm/chocolatey-packages#477]
Please republish the dd package with a checksum included. I see that you've updated it in the source here but the published version still has no checksum and as such is throwing errors on attempted install.

**Comment by tunisiano187** [comment]
Hello,
Is it still needed?
If required i can update it, but it seems it's not updated since 2015
Thank you.

**Comment by gep13** [comment]
@tunisiano187 if it is possible to push this package again, to include the checksums, then I think that this would be great.

**Comment by tunisiano187** [comment]
OK, i've asked to be maintainer and prepared the package.

**Comment by tunisiano187** [comment]
Done, this can be closed

**Comment by tunisiano187** [comment]
@gep13 , Done !
you can close this issue.
Thank you.

**Comment by gep13** [comment]
@tunisiano187 perfect, thanks.
