### ISSUE TITLE
LinkShellextension is outdated

### ISSUE THREAD

**Issue by schinagl** [dtgm/chocolatey-packages#478]
automatic/linkshellextension is heavily outdated
Since I am the author of linkshellextension, I would like to fix this.

**Comment by tunisiano187** [comment]
Now maintained by @schinagl 
https://gitlab.com/schinagl/link-shell-extension/tree/master/HardlinkExtension/install/choco

So you can close this issue too @gep13

**Comment by gep13** [comment]
@tunisiano187 thanks
