### ISSUE TITLE
Update Gramps version 5.1.1

### ISSUE THREAD

**Issue by adamvazquez82** [dtgm/chocolatey-packages#482]
Released September 15th, 2019.

https://github.com/gramps-project/gramps/releases/tag/v5.1.1

https://chocolatey.org/packages/gramps

**Comment by wroldwiedbwe** [comment]
Gramps 5.1.2 was released a few days ago.
https://github.com/gramps-project/gramps/releases/tag/v5.1.2

**Comment by tunisiano187** [comment]
I've requested to be added as maintainer, i'll push it asap.

**Comment by gep13** [comment]
@tunisiano187 thanks for doing this!
