### ISSUE TITLE
Update digiKam to version 6.4.0

### ISSUE THREAD

**Issue by temp** [dtgm/chocolatey-packages#483]
Chocolatey has 6.1.0, latest is 6.4.0

https://www.digikam.org/news/2019-11-09-6.4.0_release_announcement/

**Comment by rnc** [comment]
And 7 is in beta...

**Comment by tunisiano187** [comment]
Contacted the maintainer,

**Comment by tunisiano187** [comment]
It's waiting for approval and i already have sent the PR #541.
So you cn close it @gep13 .Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for following up here.

**Comment by temp** [comment]
@tunisiano187 I see 7.0.0 in your repo, but it is completely removed in the official sources?

**Comment by tunisiano187** [comment]
@temp, i don't really undestand your question.
The [7.0.0](https://chocolatey.org/packages)/digikam/7.0.0) is the latest on the digikam website, and it's waiting for moderation on [chocolatey](https://chocolatey.org/packages)
