### ISSUE TITLE
Bulk Rename Utility package is outdated and broken

### ISSUE THREAD

**Issue by sirinsidiator** [dtgm/chocolatey-packages#484]
I have installed "Bulk Rename Utility (Install)" version 3.0.0.1 a long time ago. For some time now, Chocolatey shows there is a version 3.1.0 available. When I try to install it, the update fails and tells me that it is unable to find a version of "bulkrenameutility" that is compatible with "bulkrenameutility.install 3.1.0.0".

That aside, there is already a version 3.3.1.0 of BRU available on its [website](https://www.bulkrenameutility.co.uk/Download.php).

**Comment by gep13** [comment]
@sirinsidiator thank you for raising this.  I believe that this has been taken care of, and a new maintainer is looking after this package:

https://github.com/dtgm/chocolatey-packages/pull/489

**Comment by sirinsidiator** [comment]
Thanks! Just updated and it works as expected.
