### ISSUE TITLE
update PingInfoView

### ISSUE THREAD

**Issue by CWempe** [dtgm/chocolatey-packages#490]
Please update PingInfoView.
https://chocolatey.org/packages/pinginfoview

The last choco version is 1.85.
But the latest official release is 2.02 and it includes some nice new features.

https://www.nirsoft.net/utils/multiple_ping_tool.html

This also results in a checksum error, because the newer ZIP-File is downloaded instead of the 1.85 version one.

**Comment by tunisiano187** [comment]
I've updated the package on my git, and requested to be maintainer.
i'll update it asap.

**Comment by gep13** [comment]
@tunisiano187 I have added you as a maintainer of this package.

Once pushed, can you send a PR into this repository.

For now, I will close out this issue.
