### ISSUE TITLE
USBLogView not installable due to update

### ISSUE THREAD

**Issue by seppestas** [dtgm/chocolatey-packages#494]
USBLogView has been updated to v1.26 and is no longer installable by chocolatey. Shouldn't the Automatic Updater automatically update the package?

The core problem is that nirsoft.net does not provide old versions, instead always updating the same zip file of software packages. This means installing old versions will not work and the checksum, and thus package installation, will fail if the package is updated.

Also, nirsoft.net and it's downloads [can be accessed over HTTPS](https://www.nirsoft.net/utils/usb_log_view.html), which is a nicer approach than using HTTP for security and privacy reasons.

**Comment by tunisiano187** [comment]
@seppestas 
I've resquested the maintainership, and i'll send it asap.

@gep13, can you assign me this issue? Thank you.

**Comment by tunisiano187** [comment]
Pushed on the website and in PR #522 here.
Now maintained on https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/usblogview

**Comment by gep13** [comment]
@tunisiano187 sounds good
