### ISSUE TITLE
Please update transmission to 2.94

### ISSUE THREAD

**Issue by pyhedgehog** [dtgm/chocolatey-packages#495]
https://chocolatey.org/packages/transmission has version 2.92
https://transmissionbt.com/download/ has 2.94

**Comment by tunisiano187** [comment]
Solved in PR #517

**Comment by tunisiano187** [comment]
@gep13 , you can close it as soon as i'm mintainer

**Comment by gep13** [comment]
@tunisiano187 thanks for picking up this package!
