### ISSUE TITLE
Please update Freeplane from 1.7.9 to 1.8.5

### ISSUE THREAD

**Issue by koppor** [dtgm/chocolatey-packages#496]
FreePlange got updated to 1.8.5.

- Download page: https://sourceforge.net/projects/freeplane/files/latest/download
- Deep link: https://netcologne.dl.sourceforge.net/project/freeplane/freeplane%20stable/Freeplane-Setup-1.8.5.exe

Changelog: https://www.freeplane.org/info/history/history_en.txt

Would it be possible to update the chocolatey package?

**Comment by nfriese** [comment]
Hi @koppor 
FreePlane got updated to 1.8.5 - the title of your issue must be updated: "Please update Freeplane from 1.7.9 to 1.8.5"

see also https://chocolatey.org/packages/FreePlane#comment-4923854411

- Download page: https://sourceforge.net/projects/freeplane/files/latest/download
- Deeplink: https://downloads.sourceforge.net/project/freeplane/freeplane%20stable/Freeplane-Setup-1.8.5.exe
- Changelog: https://www.freeplane.org/info/history/history_en.txt

I don't know whether the maintainer has switched his packet automation process to the new AU process. Or whether the maintainer is still active at all. His last activities were 2 years ago (April 2018). I'm afraid someone else will have to maintain the package.

**Comment by gep13** [comment]
@nfriese the packages in this repository are not using AU, no.  They are using another system based on ketarin.  While this system is still running, to the best of my knowledge, there are known issues with it, and packages have been moved out of this repository to other maintainers.

**Comment by cmorty** [comment]
@gep13 Is it reasonable to open a RFM?

**Comment by gep13** [comment]
@cmorty yes, that is definitely a valid approach.

**Comment by gep13** [comment]
@tunisiano187 has just taken owner maintenance of this package, and the packaging scripts have been removed from this repository.  As such, I am going to close this issue.

**Comment by koppor** [comment]
Link to the new repository: https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/freeplane

**Comment by tunisiano187** [comment]
Package pushed
