### ISSUE TITLE
OpenRA Release 20200503

### ISSUE THREAD

**Issue by Mailaender** [dtgm/chocolatey-packages#499]
latest version number: release-20200503
release date: 20200503
URL to the install binary: https://github.com/OpenRA/OpenRA/releases/download/release-20200503/OpenRA-release-20200503-x64.exe

**Comment by Mailaender** [comment]
By the way is there a way to automatize this?

**Comment by tunisiano187** [comment]
I'll take a look into this

**Comment by tunisiano187** [comment]
It seems you already have made the package, if you need to automate it, ask me ;-) i can add it to my automated repository if you want

**Comment by Mailaender** [comment]
@cjshmyr worked on this, but it seems some checks failed https://chocolatey.org/packages/openra/2020.05.03

**Comment by Mailaender** [comment]
We have our own https://github.com/OpenRA/Chocolatey abandoned repository. Maybe revive that one?

**Comment by tunisiano187** [comment]
If you want to automated it, it will need many updates. but you can use AU (https://chocolatey.org/packages/AU)

**Comment by tunisiano187** [comment]
Your package is missing some things like the packagesourceurl, and the installation parameters seems to have a problem, the installation doesn't finish.
https://gist.github.com/choco-bot/32d88ed228d25b84dfafca610678fc62#file-install-txt-L373

i see you're maintainair of OpenRA, maybe you can add the update in the CI of the main project...?

**Comment by gep13** [comment]
@Mailaender @tunisiano187 The packaging files for OpenRA have been removed from this repository, as such, I think the discussion here should move to the other repository.  Let me know if you have any questions.
