### ISSUE TITLE
Autologon checksum changed

### ISSUE THREAD

**Issue by Pilskalns** [dtgm/chocolatey-packages#562]
Hi,

As of now, `autologon` package install fails because checksums doesn't match between value saved inside install script and checksum of file downloaded from remote site (https://download.sysinternals.com/files/AutoLogon.zip)

Also, since the ZIP being downloaded is so small (less than 500KB), would it make sense to include inside the .nupkg instead on relying on the remote download always being up the same? Especially, the download path is to generic path as subject of change not linking into specific version.

Few days ago it was still fine. I checked the "new" ZIP file, it installs just fine.

**Comment by tunisiano187** [comment]
@gep13 this one can be closed too now that I am the new maintainer

**Comment by gep13** [comment]
@tunisiano187 sounds good
