### ISSUE TITLE
The pwgen package is outdated

### ISSUE THREAD

**Issue by Mikaela** [dtgm/chocolatey-packages#566]
The version of pwgen package in Chocolatey is 2.9.0 which offers update from the website that is 3.2.0.

* https://sourceforge.net/projects/pwgen-win/files/Password%20Tech/

**Comment by tunisiano187** [comment]
I'll take this package to update it

**Comment by gep13** [comment]
@tunisiano187 thanks for picking up this package, I will go ahead and close out this issue.
