### ISSUE TITLE
OpenRA checksum tests will always fail

### ISSUE THREAD

**Issue by Mailaender** [dtgm/chocolatey-packages#57]
It creates broken packages, see https://github.com/OpenRA/OpenRAWeb/pull/260#issuecomment-143523057.

**Comment by Mailaender** [comment]
See https://gist.github.com/choco-bot/85ca3ef36ae9cf3334a5

**Comment by ferventcoder** [comment]
Not sure if the checksum grabber is valid - look at the etag header:

~~~sh
==> default:  DEBUG:   'ETag':'"1239d48aa7889555aa65d1d1d5860d61"'
~~~
This matches against how the checksum actually comes out. 

@Mailaender @dtgm do you know of a reason that the checksums would be different on different downloads?

**Comment by Mailaender** [comment]
The EXE's are build from @travis-ci and uploaded to https://github.com/OpenRA/OpenRA/releases Their checksums should not change after a release has been tagged.

**Comment by dtgm** [comment]
@ferventcoder you are correct, the regex was not capturing the correct string. I've fixed this. https://chocolatey.org/packages/openra/2015.12.24.20151227

**Comment by Mailaender** [comment]
Thanks!
