### ISSUE TITLE
LastActivityView is out of date

### ISSUE THREAD

**Issue by chanibal** [dtgm/chocolatey-packages#574]
There is a checksum issue. Not surprising, as bundled version is 1.32 and current is 1.35

>ERROR: Checksum for '(...)\1.32\lastactivityview.zip' did not meet '8572b903d316b55e89fa7c129a7c8d0e1da597158fcde8a7210b2b1a6e34df17' (...)

Your package structure suggests that its automatically generated, so no pull request unless requested.

**Comment by tunisiano187** [comment]
I'll try to take it this weekend if it's OK

**Comment by tunisiano187** [comment]
OK, i've requested to be added as maintainer, and it's ready on my repository, so as soone it's  approved, it will be pushed.

**Comment by gep13** [comment]
@tunisiano187 thanks for your help!
