### ISSUE TITLE
pngquant is out of date

### ISSUE THREAD

**Issue by seisman** [dtgm/chocolatey-packages#577]
The current version available from chocolatey is v2.12.3 (https://chocolatey.org/packages/pngquant), but the official latest version is v2.13.1 (https://pngquant.org/).

Installing pngquant gives me the following error:

```
Download of pngquant-windows.zip (384.23 KB) completed.
Error - hashes do not match. Actual value was '587E49904B58C8E69DF7A71CEABFD8EFCCDD79E8998062AA99C6411856510E7D'.
ERROR: Checksum for 'C:\Users\runneradmin\AppData\Local\Temp\chocolatey\pngquant\2.12.3\pngquant-windows.zip' did not meet '7ee4f98c7c0dfd23807b624a90a2aa3108ed46bc01f1bbd322bb9e3f3f54e6a6' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.

```

**Comment by gep13** [comment]
@tunisiano187 is this one that you could perhaps help with?

**Comment by tunisiano187** [comment]
Yes, i'll update it

Le ven. 8 janv. 2021 08:16, Gary Ewan Park <notifications@github.com> a
écrit :

**Comment by tunisiano187** [comment]
https://github.com/dtgm/chocolatey-packages/pull/578

**Comment by gep13** [comment]
@tunisiano187 thank you for picking up this package!
