### ISSUE TITLE
macrocreator macrocreator.install macrocreator.portable outdated

### ISSUE THREAD

**Issue by jkolonko** [dtgm/chocolatey-packages#583]
All of these packages have version 5.0.5 whereas 5.4.0 is the current release.

**Comment by tunisiano187** [comment]
I'll Update it, thank you for the information

**Comment by tunisiano187** [comment]
@gep13 sorry for the spam ;-) 
It's ready to be updated this night, i've requested the maintainership.
Pauby already added me on the .install, but i've just introduced the request for the meta package and the portable.

So you can close this issue.

Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for your help with this package!
