### ISSUE TITLE
Apps with self-deprecating URL builds

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#6]
**[Pulse](https://github.com/dtgm/chocolatey-packages/tree/master/automatic/pulse)** 
Latest `http://download.ind.ie/pulse/latest/`
Previous `http://download.ind.ie/pulse/0.1.3`
HOLD: releases have been suspended during alpha phase

~~**[FreePlane](https://github.com/dtgm/chocolatey-packages/tree/master/automatic/freeplane)**
Latest stable build `http://sourceforge.net/projects/freeplane/files/freeplane%20stable/`
Previous stable build gets moved to `http://sourceforge.net/projects/freeplane/files/freeplane%20stable/archive/`~~
FIXED: https://sourceforge.net/p/freeplane/featurerequests/2173/

**Comment by dtgm** [comment]
[Atom](https://chocolatey.org/packages/Atom)
Latest `https://atom.io/download/windows`
Fix `https://github.com/atom/atom/releases/download/v0.187.0/AtomSetup.exe`

https://github.com/atom/atom/issues/5016

https://github.com/atom/chocolatey/issues/28
https://github.com/atom/atom/issues/2729

https://github.com/atom/chocolatey/issues/31#issuecomment-66498520
http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html

**Comment by tunisiano187** [comment]
@gep13 , i think this one can be closed.
Atom and freeplane are maintained by other maintainers and pulse hasn't been update since 2015

Thank you

**Comment by gep13** [comment]
@tunisiano187 sounds good.
