### ISSUE TITLE
winrar v6.0.0.20210102 checksum mismatch

### ISSUE THREAD

**Issue by mq2195** [dtgm/chocolatey-packages#601]
choco install -y winrar

Error - hashes do not match. Actual value was 'B422D22BA8E0AF59672D3720161B9DE92C2BC56956AC18F847595B8AA84CDEB9'.
ERROR: Checksum for 'C:\Users\user\AppData\Local\Temp\chocolatey\winrar\6.0.0.20210102\winrar-x64-600pl.exe' did not meet '0e53870be13dda3b6e8063b976871463ae5daf708a5375f982075752c6e80e27' for checksum type 'sha256'. Consider passing th
e actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of winrar was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winrar\tools\chocolateyInstall.ps1'.

workaround:
choco install -y winrar --params="/English"

**Comment by gep13** [comment]
Since the winrar package is now maintained by another maintainer, I am going to close ahead and close out this issue.
