### ISSUE TITLE
GraphicsMagick is now 1.3.36

### ISSUE THREAD

**Issue by BrandonKMLee** [dtgm/chocolatey-packages#605]
Check https://sourceforge.net/projects/graphicsmagick/files/
Also the original pack is updated o 16 Jun 2019, which is 22 months ago!

**Comment by TakataSanshiro** [comment]
@BrandonKMLee I've updated the package. Thanks for your notice.
https://community.chocolatey.org/packages/graphicsmagick/1.3.36

**Comment by gep13** [comment]
@TakataSanshiro Thanks for taking over maintenance of this package.  I have made a commit to remove the packaging files from this repository:

https://github.com/dtgm/chocolatey-packages/commit/ff2379cb17da00d444987738c4ee7869cc56b457
