### ISSUE TITLE
Add Embarcadero Dev-C++

### ISSUE THREAD

**Issue by rollingmoai** [dtgm/chocolatey-packages#606]
`orwelldevcpp` is quite old, it might be good to add this new active fork: https://github.com/Embarcadero/Dev-Cpp.

**Comment by tunisiano187** [comment]
Hello,
dtgm isn't active anymore.
To help, i've created the package [embarcaderodevcpp](https://community.chocolatey.org/packages/embarcaderodevcpp)
if it's OK for you, you can close this issue.

Have a nice day
