### ISSUE TITLE
ExifToolGUI is broken

### ISSUE THREAD

**Issue by RJHsiao** [dtgm/chocolatey-packages#609]
Hi dtmg,

Package ExifToolGUI cannot download anymore because of the website moved.
The new URLs are:
* Website & Manual: https://exiftool.org/gui/
* Forum & Changelog: https://exiftool.org/forum/index.php?topic=2750.0
* Metadata articles: https://exiftool.org/gui/articles/
* Download Link: https://exiftool.org/gui/exiftoolgui516.zip

It looks like some script will generate automatically so I shouldn't edit them directly, and I can't find the way to correct the parameters about that.
Please help to fix them when you see this.
Thank you!

**Comment by RJHsiao** [comment]
Hey!
Is anyone here?

**Comment by TakataSanshiro** [comment]
I've submitted the update package. It passed the testing.
https://community.chocolatey.org/packages/exiftoolgui/5.16.20211222

You can confirm that with this command before approve one.
`choco install -y exiftoolgui --version 5.16.20211222`
Thanks for your notification. @RJHsiao

**Comment by RJHsiao** [comment]
Thank you @TakataSanshiro 
I see you push the update in last week, and it can be upgrade successfully that I just check right now.
