### ISSUE TITLE
git-annex is now >= 8.20210804

### ISSUE THREAD

**Issue by riedel** [dtgm/chocolatey-packages#610]
See https://downloads.kitenet.net/git-annex/windows/current/git-annex-installer.exe.info

**Comment by unforgettableid** [comment]
@dtgm has been gone, and has made zero commits, for years now.

In general, if you contact a package maintainer about an outdated package, and there's no been reply after a week, it's a good idea to [contact the Chocolatey site admins](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process:~:text=If%20the%20maintainer(s)%20do%5Bes%5D%20not%20respond%20after%20one%20week%2C%20use%20the%20%22Contact%20Site%20Admins%22%20link%20to%20contact%20the%20site%20Moderators%2C%20who%20will%20attempt%20to%20triage%20the%20situation%20and%20make%20a%20determination%20if%20the%20package%20is%20abandoned.) next.  You can ask them to have someone else take over maintenance of the package.

**Comment by tunisiano187** [comment]
I'll tke this package to update it

**Comment by tunisiano187** [comment]
Hello, @riedel, you can close this issue, i have updated the package.

Thank you

**Comment by riedel** [comment]
sure!
