### ISSUE TITLE
Cmder does not produce start menu shortcut

### ISSUE THREAD

**Issue by midrare** [dtgm/chocolatey-packages#614]
As of now, cmder can only be started from the command line or the run menu. It'd be convenient if there was a shortcut created in the start menu as well.

**Comment by tunisiano187** [comment]
Hello!
The package is maintained by @AdmiringWorm here : https://github.com/AdmiringWorm/chocolatey-packages/tree/master/automatic/cmder
Maybe you should consider to create the issue on that repository ? https://github.com/AdmiringWorm/chocolatey-packages/issues

@AdmiringWorm , shouldn't you remove the package from here to avoid confusion ?
and by the way, it sems you're still using the broken github system to update the package, you now need to use api.github.com to have your package working again.
Thank you

**Comment by gep13** [comment]
It doesn't look like the `cmder` package files are in this repository, so I am going to close out this issue.
