### ISSUE TITLE
Update request: filetypesman

### ISSUE THREAD

**Issue by jwfxpr** [dtgm/chocolatey-packages#619]
Current chocolatey package version: 1.85
Current available version: 1.95

Download page: https://www.nirsoft.net/utils/file_types_manager.html

**Comment by TakataSanshiro** [comment]
I submitted the update package. It has been approved.
https://community.chocolatey.org/packages/FileTypesMan/1.96

Thanks for your notification. @jwfxpr

**Comment by tunisiano187** [comment]
@gep13 ,can you close this issue?
Thank you
