### ISSUE TITLE
Upgrade the gsmartcontrol package

### ISSUE THREAD

**Issue by rgl** [dtgm/chocolatey-packages#621]
Can you please upgrade the [gsmartcontrol package to 1.1.4](https://github.com/ashaduri/gsmartcontrol/releases/tag/v1.1.4)?

**Comment by unforgettableid** [comment]
@dtgm has been gone, and has made zero commits, for years now.  I sent a message to the Chocolatey site admins today, asking them to have someone else please take over maintenance of the relevant Chocolatey package.

In general, if you contact a package maintainer about an outdated package, and there's no reply after a week, it's a good idea to [contact the Chocolatey site admins](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process:~:text=If%20the%20maintainer(s)%20do%5Bes%5D%20not%20respond%20after%20one%20week%2C%20use%20the%20%22Contact%20Site%20Admins%22%20link%20to%20contact%20the%20site%20Moderators%2C%20who%20will%20attempt%20to%20triage%20the%20situation%20and%20make%20a%20determination%20if%20the%20package%20is%20abandoned.) next.

**Comment by unforgettableid** [comment]
As per the Chocolatey team's instructions, I've opened a [request](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1360) for a new maintainer to step up.  Is any Chocolatey user out there possibly interested in volunteering?

**Comment by tunisiano187** [comment]
Hello, I'll take it

**Comment by unforgettableid** [comment]
Dear @rgl:

Tunisiano's gsmartcontrol 1.1.4 package is now available.  Please do close this issue, when you have time.

Thank you!

**Comment by rgl** [comment]
Thank You!
