### ISSUE TITLE
Upgrade ProduKey package to 1.97

### ISSUE THREAD

**Issue by C-Duv** [dtgm/chocolatey-packages#622]
The [`ProduKey`](https://community.chocolatey.org/packages?q=ProduKey) Chocolatey packages are installing v1.92 and v1.93 but [ProduKey](https://www.nirsoft.net/utils/product_cd_key_viewer.html) version 1.97 is available.

The packages in this repository are supposed to be automatic but obviously it failed for theses since v1.93

I know how to create a package but not with Ketarin. How can I help?

* latest version number: 1.97
* release date: 2021-04-18
* URL to the install binary:
  * For `produkey.install`:
    * x86 & x64: https://www.nirsoft.net/utils/produkey_setup.exe
  * For `produkey.portable`:
    * x86: https://www.nirsoft.net/utils/produkey.zip
    * x64: https://www.nirsoft.net/utils/produkey-x64.zip

**Comment by unforgettableid** [comment]
@dtgm has been gone, and has made zero commits, for years now.

In general, if you contact a package maintainer about an outdated package, and there's no been reply after a week, it's a good idea to [contact the Chocolatey site admins](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process:~:text=If%20the%20maintainer(s)%20do%5Bes%5D%20not%20respond%20after%20one%20week%2C%20use%20the%20%22Contact%20Site%20Admins%22%20link%20to%20contact%20the%20site%20Moderators%2C%20who%20will%20attempt%20to%20triage%20the%20situation%20and%20make%20a%20determination%20if%20the%20package%20is%20abandoned.) next.  You can ask them to have someone else take over maintenance of the package.

**Comment by tunisiano187** [comment]
You can use Au module if you want but it needs to be on another repo.
you can check here to see an exemple (and even push it there to automate it) 
https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/handle

**Comment by TakataSanshiro** [comment]
I'm familiar with nirsoft packages.
I submitted the update packages. They have been approved.
https://community.chocolatey.org/packages/ProduKey/1.97
https://community.chocolatey.org/packages/produkey.install/1.97
https://community.chocolatey.org/packages/produkey.portable/1.97

Thanks for your notification. @C-Duv

**Comment by tunisiano187** [comment]
@C-Duv , as it's solved, can you close this issue ?
Thank you.

**Comment by C-Duv** [comment]
:+1:
