### ISSUE TITLE
Handle has checksum mismatch

### ISSUE THREAD

**Issue by slycordinator** [dtgm/chocolatey-packages#625]
For Handle v4.22
chocolatey downloads from 'https://download.sysinternals.com/files/Handle.zip'

upstream file sh256 sum:            '524e61547c8e26608cda1b11b6e9471616cccc48530f6e7ec9131eabf839357e'

chocolatey package sh256 sum: '1f2e6eda07f0581c1cfac733f34005c9122c4d2a9d5e0b6d99797502a76ad79e'

**Comment by slycordinator** [comment]
Also, in tools/chocolateyInstall.ps1
it seems like

$checksumType64 = "checksumType"
should be
$checksumType64 = "$checksumType"

**Comment by tunisiano187** [comment]
I'll take the package to my repository to update it.

**Comment by tunisiano187** [comment]
@slycordinator, the package is updated.
You can close this request ;-)
Have a nice day

**Comment by slycordinator** [comment]
> @slycordinator, the package is updated. You can close this request ;-) Have a nice day

Thanks for the quick fix/update.

Sorry for getting to closing this so late....
