### ISSUE TITLE
fossil.portable has invalid download URLs

### ISSUE THREAD

**Issue by pyhedgehog** [dtgm/chocolatey-packages#63]
`fossil.portable-0.34` attempts to download http://www.fossil-scm.org/download/fossil-w32-20150119112900.zip when fossil [download page](http://www.fossil-scm.org/download.html) refers https://www.fossil-scm.org/download/fossil-w32-1.34.zip
Same for 0.30.
```console
 Attempt to get headers for http://www.fossil-scm.org/download/fossil-w32-20150119112900.zip failed.
   Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
 Downloading fossil 32 bit
   from 'http://www.fossil-scm.org/download/fossil-w32-20150119112900.zip'
 WARNING: Write-ChocolateyFailure is deprecated. If you are the package maintainer, please use 'throw $_.Exception' instead.
 Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
 C:\ProgramData\chocolatey\helpers\functions\Write-ChocolateyFailure.ps1:24 знак:3
 +   throw "$failureMessage"
 +   ~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: (Exception calli...04) Not Found.":String) [], RuntimeException
     + FullyQualifiedErrorId : Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of fossil.portable was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\fossil.portable\tools\chocolateyInstall.ps1'.
 See log for details.
0.34 not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"
```

**Comment by dtgm** [comment]
What is the chocolatey command you use?

By default, the last approved version will be installed, in this case 1.30.  Version 1.34 has not been moderated yet so to force that version to install you must pass `-version 1.34`

PS C:\> `choco install fossil.portable -version 1.34 -y`
>Chocolatey v0.9.10-beta1
Installing the following packages:
fossil.portable
By installing you accept licenses for the packages.

>fossil.portable v1.34
 Downloading fossil.portable 32 bit
   from 'https://www.fossil-scm.org/download/fossil-w32-1.34.zip'
 Hashes match.
 Extracting C:\Users\x\AppData\Local\Temp\chocolatey\fossil.portable\1.34\fossil.portableInstall.zip to C:\ProgramData\chocolatey\lib\fossil.portable\tools...
 7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
 Processing archive: C:\Users\x\AppData\Local\Temp\chocolatey\fossil.portable\1.34\fossil.portableInstall.zip
 Extracting  fossil.exe
 Everything is Ok
 Size:       4382208
 Compressed: 1819562
 C:\ProgramData\chocolatey\lib\fossil.portable\tools
 ShimGen has successfully created a shim for fossil.exe
 The install of fossil.portable was successful.

>Chocolatey installed 1/1 package(s). 0 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
