### ISSUE TITLE
adexplorer validation issue

### ISSUE THREAD

**Issue by wjk** [dtgm/chocolatey-packages#69]
While I was browsing Chocolatey.org, I noticed that your `adexplorer` package has failed validation. I was looking at the log, and noticed that the failure was due to syntax errors in the install PowerShell script. To wit: `-not` is the correct syntax for negating a test in an if block. [`!` is incorrect](https://github.com/dtgm/chocolatey-packages/blob/master/automatic/_output/adexplorer/1.44/tools/chocolateyInstall.ps1#L21-L22). I can submit a PR if it would help.

**Comment by dtgm** [comment]
Thanks for looking into the issue and reporting it!

A PR is always welcome!

**Comment by dtgm** [comment]
https://gist.github.com/choco-bot/b168f299c658d2d974fe#file-install-txt-L168-L172

! or -not are both correct, but I forgot the parenthesis after the op 

e.g. `if (-not(Test-Path C:\foo\bar)){"Path does not exist"}`

I'll change to `-not` since that is more clear than `!`
