### ISSUE TITLE
Sysinternals packages temporarily broken

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#80]
>Sysinternals downloads are currently broken (some casing change on the technet site). In the meantime use https://live.sysinternals.com 

https://twitter.com/markrussinovich/status/687273684793360384

Also, see sysinternals [help forum](http://forum.sysinternals.com/process-explorer-v161-broken-link_topic31895.html)

**Comment by yakimant** [comment]
But small letter is working for me, try:
https://download.sysinternals.com/files/coreinfo.zip

**Comment by dtgm** [comment]
Correct. If it wasn't clear from what Mark said, it appears TechNet has enforced character case matching so requesting https://download.sysinternals.com/files/Coreinfo.zip won't find coreinfo.zip as its stored on the server.

Chocolatey packages are immutable which would require updating all the sysinternals package so hopefully this can be fixed on Sysinternals/Technet's side.

Additionally, since someone changed all the URLs on the Technet site so they will find the proper case, when new versions of sysinternals utilities are released, the corresponding choco pkg I maintain will have the updated correct URL.

**Comment by dtgm** [comment]
Some old URLs are working again. Others are not. Copying https://github.com/dtgm/chocolatey-packages/issues/70#issuecomment-172814882 to here.  

Checked == working

Maintained by me:  
- [x] https://download.sysinternals.com/files/AccessChk.zip
- [x] https://download.sysinternals.com/files/AccessEnum.zip
- [x] https://download.sysinternals.com/files/AdExplorer.zip
- [ ] https://download.sysinternals.com/files/AdInsight.zip
- [ ] https://download.sysinternals.com/files/ADRestore.zip
- [ ] https://download.sysinternals.com/files/AutoLogon.zip
- [x] https://download.sysinternals.com/files/Autoruns.zip
- [ ] https://download.sysinternals.com/files/CacheSet.zip
- [ ] https://download.sysinternals.com/files/ClockRes.zip
- [ ] https://download.sysinternals.com/files/Coreinfo.zip
- [x] https://download.sysinternals.com/files/Ctrl2Cap.zip
- [x] https://download.sysinternals.com/files/DiskExt.zip
- [ ] https://download.sysinternals.com/files/DiskMon.zip
- [x] https://download.sysinternals.com/files/DiskView.zip
- [ ] https://download.sysinternals.com/files/EFSDump.zip
- [ ] https://download.sysinternals.com/files/FindLinks.zip
- [ ] https://download.sysinternals.com/files/Hex2Dec.zip
- [ ] https://download.sysinternals.com/files/Junction.zip
- [ ] https://download.sysinternals.com/files/LdmDump.zip
- [x] https://download.sysinternals.com/files/ListDlls.zip
- [x] https://download.sysinternals.com/files/LiveKD.zip
- [ ] https://download.sysinternals.com/files/logonSessions.zip
- [ ] https://download.sysinternals.com/files/NTFSInfo.zip
- [x] https://download.sysinternals.com/files/PendMoves.zip
- [x] https://download.sysinternals.com/files/PipeList.zip
- [x] https://download.sysinternals.com/files/PortMon.zip
- [x] https://download.sysinternals.com/files/Procdump.zip
- [x] https://download.sysinternals.com/files/Regdelnull.zip
- [x] https://download.sysinternals.com/files/RU.zip
- [ ] https://download.sysinternals.com/files/ShareEnum.zip
- [ ] https://download.sysinternals.com/files/Sigcheck.zip
- [x] https://download.sysinternals.com/files/Strings.zip
- [x] https://download.sysinternals.com/files/Sync.zip
- [x] https://download.sysinternals.com/files/VMMap.zip
- [x] https://download.sysinternals.com/files/VolumeId.zip
- [x] https://download.sysinternals.com/files/WhoIs.zip
- [x] https://download.sysinternals.com/files/WinObj.zip
- [x] https://download.sysinternals.com/files/ZoomIt.zip

**Comment by dtgm** [comment]
https://chocolatey.org/packages/AccessChk
https://chocolatey.org/packages/AccessEnum
https://chocolatey.org/packages/AdExplorer
https://chocolatey.org/packages/AdInsight
https://chocolatey.org/packages/ADRestore
https://chocolatey.org/packages/AutoLogon
https://chocolatey.org/packages/CacheSet
https://chocolatey.org/packages/ClockRes
https://chocolatey.org/packages/Coreinfo
https://chocolatey.org/packages/Ctrl2Cap
https://chocolatey.org/packages/DiskExt
https://chocolatey.org/packages/DiskMon
https://chocolatey.org/packages/DiskView
https://chocolatey.org/packages/EFSDump
https://chocolatey.org/packages/FindLinks
https://chocolatey.org/packages/Hex2Dec
https://chocolatey.org/packages/Junction
https://chocolatey.org/packages/LdmDump
https://chocolatey.org/packages/ListDlls
https://chocolatey.org/packages/LiveKD
https://chocolatey.org/packages/logonSessions
https://chocolatey.org/packages/NTFSInfo
https://chocolatey.org/packages/PendMoves
https://chocolatey.org/packages/PipeList
https://chocolatey.org/packages/PortMon
https://chocolatey.org/packages/Regdelnull
https://chocolatey.org/packages/RU
https://chocolatey.org/packages/ShareEnum
https://chocolatey.org/packages/Sigcheck
https://chocolatey.org/packages/Strings
https://chocolatey.org/packages/Sync
https://chocolatey.org/packages/VMMap
https://chocolatey.org/packages/VolumeId
https://chocolatey.org/packages/WhoIs
https://chocolatey.org/packages/WinObj 

https://chocolatey.org/packages/Autoruns
https://chocolatey.org/packages/BGInfo
https://chocolatey.org/packages/DebugView
https://chocolatey.org/packages/Disk2vhd
https://chocolatey.org/packages/Handle
https://chocolatey.org/packages/Procdump
https://chocolatey.org/packages/ProcessExplorer
https://chocolatey.org/packages/ProcessMonitor
https://chocolatey.org/packages/PSTools
https://chocolatey.org/packages/TCPView
https://chocolatey.org/packages/ZoomIt
