### ISSUE TITLE
Create PSTools package for dependent PS utilities

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#82]
> all of the PS utilities have the same download url - you should consider a PSTools package that each of them depends on

Noted in https://github.com/dtgm/chocolatey-packages/issues/70#issuecomment-167629466

**Comment by tunisiano187** [comment]
@gep13 , i don't know if it is linked, but @fervencoder as created it, so this one can be closed too.
(orry i give you a lot of things to do ...)
Thank you

**Comment by gep13** [comment]
@tunisiano187 I think you are right.
