### ISSUE TITLE
qttabbar 1038.0 fails to install

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#84]
[qttabbar-1038.0](https://chocolatey.org/packages/QTTabBar/1038.0)'s AHK was written for Win8. It is not compatible with Win10 and hangs when trying to register the addon within IE.

```
Types registered successfully
qttabbar has been installed.
HKEY_CURRENT_USER\Software\Quizo
HKEY_CURRENT_USER\Software\Quizo\QTTabBar
Attempting to automatically add QTTabBar to File Explorer, this may take a minute...
Cannot find path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main' because it does not exist.
Cannot find path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main' because it does not exist.
Cannot find path 'HKCU:\Software\Policies\Microsoft\Internet Explorer\Main' because it does not exist.
Cannot find path 'HKCU:\Software\Policies\Microsoft\Internet Explorer\Main' because it does not exist.
Cannot find path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main' because it does not exist.
Cannot find path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main' because it does not exist.
Cannot find path 'HKCU:\Software\Policies\Microsoft\Internet Explorer\Main' because it does not exist.
Cannot find path 'HKCU:\Software\Policies\Microsoft\Internet Explorer\Main' because it does not exist.
```

**Comment by dtgm** [comment]
Despite the errors above, qttabbar does install and uninstall via chocolatey. On 2nd attempt:

```
cuninst qttabbar -y
cinst qttabbar -version 1038.0 -y
...
Installing qttabbar...
```

then I receive a NullReferenceException messagebox:

```
---------------------------

---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at RegisterQTTabBar.InstallerForm.CreateStartMenuITems(Boolean fInstall)
---------------------------
OK   
---------------------------
```

then the AHK script works correctly by enabling the addon within IE. The only difference this time was IE was already open; probably just needs to increase the delay for IE to instantiate its UI.

**Comment by tunisiano187** [comment]
@gep13 , now maintained by @mwrock
you can close it.
Thank you

**Comment by gep13** [comment]
@tunisiano187 I am fairly sure that @mwrock isn't in a position to maintain packages anymore either.  If this is a package that you are interested in helping with, we could get you added to that one as well.  It would also seem that @dtgm was the last person to push a package version for this package, so I suspect that he took over maintenance from @mwrock.

**Comment by tunisiano187** [comment]
Yes, I'll take a look at it tomorrow.

**Comment by tunisiano187** [comment]
FYI : i'm solving problems with other of my packages, and i'll try this one after.
It seems the newer version isn't a complete one but only an update, so i'll need to test if we can set a depedency on a previous version of the same package... Do you know if it's possible?
if it don't work i'll install them both in the package.

**Comment by gep13** [comment]
@tunisiano187 I am not sure if I fully understand what you are asking here.  What I would say is, if you have specific packaging related questions, it is perhaps better to raise them in the Gitter room, where more folks would be able to help you.
