### ISSUE TITLE
7zip 15.11 extracts CABs, 15.14 no longer does

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#95]
Extracted with 7z 15.14

```
C:\SelfExtractingCab
└───.rsrc
    ├───DIALOG
    └───MANIFEST
```

Extracted with 7z 15.14

```
C:\SelfExtractingCab
├───Dependency1
└───Dependency2
```

**Comment by tunisiano187** [comment]
@gep13 , this is now in the coreteam, so it can be closed too

**Comment by gep13** [comment]
@tunisiano187 I think that this is a different issue, but happy for it to be closed.
