### ISSUE TITLE
why are these pkgs tagged notSilent?

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#98]
`$ for i in $(grep -liP '(?<=\<tags\>).*notsilent' */*.nuspec); do echo - [ ] $i; done`
- [ ] adblockpluschrome.work/adblockpluschrome.nuspec
- [ ] adblockplusfirefox.work/adblockplusfirefox.nuspec
- [ ] adblockplusopera.work/adblockplusopera.nuspec
- [ ] adblockplussafari.handover/adblockplussafari.nuspec
- [ ] avgpctuneup.handover/avgpctuneup.nuspec
- [ ] avirafreeantivirus.handover/avirafreeantivirus.nuspec
- [ ] aviraiss.handover/aviraiss.nuspec
- [ ] bitdefenderavfree.handover/bitdefenderavfree.nuspec
- [ ] clamwin/clamwin.nuspec
- [ ] f-secureav.handover/f-secureav.nuspec
- [ ] f-secureis.handover/f-secureis.nuspec
- [ ] kss/kss2.nuspec
- [ ] spideroak.handover/spideroak.nuspec
- [x] template-all/foo-comments.nuspec
- [x] template-exe-inno/abcprog.nuspec
- [x] template-exe-nsis/abcprog.nuspec
- [x] template-msi/abcprog.nuspec
- [ ] ultravnc/ultravnc.nuspec
- [ ] vcredist2005/vcredist2005.nuspec
- [ ] vcredist2008/vcredist2008.nuspec
- [ ] webpi.handover/webpi.nuspec
- [ ] windowsessentials/windowsessentials.nuspec

Related:
Fixed AHK pkgs containing notSilent: https://github.com/dtgm/chocolatey-packages/issues/97

**Comment by dtgm** [comment]
"flags" [per ferventcoder](https://gitter.im/chocolatey/chocolatey.org?at=56af6fb9eaf741c118d6238e) (probably meant tags?)

`silent` = no screens pop up
`unattended` = may have screens pop up, but AHK or some other technology deals with that. Does not require the user to interact with the install
`notSilent` = no way to remove needing a user to click on something

**Comment by dtgm** [comment]
Update: 2016.05.07

adgellida established the `notSilent` precedent.
Of the 55 packages tagged notSilent, 44 of them are maintained by adgellida, who is no longer a contributor. 

55 packages still use `notSilent` https://chocolatey.org/packages?q=tag%3AnotSilent
20 packages by dtgm

Most of the pkgs above were inherited from adgellida and require user-interaction to finish install. They have not been fixed yet.

**Comment by gep13** [comment]
Going to go ahead and close this out. The information here is useful, but I don't think there are any actions left in this issue.
